let fffiles = `
./embed-env/share/jupyter/kernels/xr/resources/call.R
./embed-env/share/jupyter/kernels/xr/resources/comm.R
./embed-env/share/jupyter/kernels/xr/resources/completion.R
./embed-env/share/jupyter/kernels/xr/resources/configure.R
./embed-env/share/jupyter/kernels/xr/resources/execute.R
./embed-env/share/jupyter/kernels/xr/resources/inspect.R
./embed-env/share/jupyter/kernels/xr/resources/jsonlite.R
./embed-env/share/jupyter/kernels/xr/resources/log.R
./embed-env/share/jupyter/kernels/xr/resources/options.R
./embed-env/share/jupyter/kernels/xr/resources/routines.R
./embed-env/share/jupyter/kernels/xr/resources/setup.R
./embed-env/share/jupyter/kernels/xr/resources/utils.R
./embed-env/lib/R/etc/repositories
./embed-env/lib/R/etc/Renviron
./embed-env/lib/R/include/R.h
./embed-env/lib/R/include/R_ext/Altrep.h
./embed-env/lib/R/include/R_ext/Applic.h
./embed-env/lib/R/include/R_ext/Arith.h
./embed-env/lib/R/include/R_ext/BLAS.h
./embed-env/lib/R/include/R_ext/Boolean.h
./embed-env/lib/R/include/R_ext/Callbacks.h
./embed-env/lib/R/include/R_ext/Complex.h
./embed-env/lib/R/include/R_ext/Connections.h
./embed-env/lib/R/include/R_ext/Constants.h
./embed-env/lib/R/include/R_ext/Error.h
./embed-env/lib/R/include/R_ext/GetX11Image.h
./embed-env/lib/R/include/R_ext/GraphicsDevice.h
./embed-env/lib/R/include/R_ext/GraphicsEngine.h
./embed-env/lib/R/include/R_ext/Itermacros.h
./embed-env/lib/R/include/R_ext/Lapack.h
./embed-env/lib/R/include/R_ext/Linpack.h
./embed-env/lib/R/include/R_ext/MathThreads.h
./embed-env/lib/R/include/R_ext/Memory.h
./embed-env/lib/R/include/R_ext/Parse.h
./embed-env/lib/R/include/R_ext/Print.h
./embed-env/lib/R/include/R_ext/PrtUtil.h
./embed-env/lib/R/include/R_ext/QuartzDevice.h
./embed-env/lib/R/include/R_ext/RS.h
./embed-env/lib/R/include/R_ext/RStartup.h
./embed-env/lib/R/include/R_ext/Rallocators.h
./embed-env/lib/R/include/R_ext/Random.h
./embed-env/lib/R/include/R_ext/Rdynload.h
./embed-env/lib/R/include/R_ext/Riconv.h
./embed-env/lib/R/include/R_ext/Utils.h
./embed-env/lib/R/include/R_ext/Visibility.h
./embed-env/lib/R/include/R_ext/eventloop.h
./embed-env/lib/R/include/R_ext/libextern.h
./embed-env/lib/R/include/R_ext/stats_package.h
./embed-env/lib/R/include/R_ext/stats_stubs.h
./embed-env/lib/R/include/Rconfig.h
./embed-env/lib/R/include/Rdefines.h
./embed-env/lib/R/include/Rembedded.h
./embed-env/lib/R/include/Rinterface.h
./embed-env/lib/R/include/Rinternals.h
./embed-env/lib/R/include/Rmath.h
./embed-env/lib/R/include/Rversion.h
./embed-env/lib/R/lib/libRblas.so
./embed-env/lib/R/lib/libRlapack.so
./embed-env/lib/R/library/base/CITATION
./embed-env/lib/R/library/base/DESCRIPTION
./embed-env/lib/R/library/base/INDEX
./embed-env/lib/R/library/base/Meta/Rd.rds
./embed-env/lib/R/library/base/Meta/demo.rds
./embed-env/lib/R/library/base/Meta/features.rds
./embed-env/lib/R/library/base/Meta/hsearch.rds
./embed-env/lib/R/library/base/Meta/links.rds
./embed-env/lib/R/library/base/Meta/package.rds
./embed-env/lib/R/library/base/R/Rprofile
./embed-env/lib/R/library/base/R/base
./embed-env/lib/R/library/base/R/base.rdb
./embed-env/lib/R/library/base/R/base.rdx
./embed-env/lib/R/library/base/demo/error.catching.R
./embed-env/lib/R/library/base/demo/is.things.R
./embed-env/lib/R/library/base/demo/recursion.R
./embed-env/lib/R/library/base/demo/scoping.R
./embed-env/lib/R/library/compiler/DESCRIPTION
./embed-env/lib/R/library/compiler/INDEX
./embed-env/lib/R/library/compiler/Meta/Rd.rds
./embed-env/lib/R/library/compiler/Meta/features.rds
./embed-env/lib/R/library/compiler/Meta/hsearch.rds
./embed-env/lib/R/library/compiler/Meta/links.rds
./embed-env/lib/R/library/compiler/Meta/nsInfo.rds
./embed-env/lib/R/library/compiler/Meta/package.rds
./embed-env/lib/R/library/compiler/NAMESPACE
./embed-env/lib/R/library/compiler/R/compiler
./embed-env/lib/R/library/compiler/R/compiler.rdb
./embed-env/lib/R/library/compiler/R/compiler.rdx
./embed-env/lib/R/library/datasets/DESCRIPTION
./embed-env/lib/R/library/datasets/INDEX
./embed-env/lib/R/library/datasets/Meta/Rd.rds
./embed-env/lib/R/library/datasets/Meta/data.rds
./embed-env/lib/R/library/datasets/Meta/features.rds
./embed-env/lib/R/library/datasets/Meta/hsearch.rds
./embed-env/lib/R/library/datasets/Meta/links.rds
./embed-env/lib/R/library/datasets/Meta/nsInfo.rds
./embed-env/lib/R/library/datasets/Meta/package.rds
./embed-env/lib/R/library/datasets/NAMESPACE
./embed-env/lib/R/library/datasets/data/Rdata.rdb
./embed-env/lib/R/library/datasets/data/Rdata.rds
./embed-env/lib/R/library/datasets/data/Rdata.rdx
./embed-env/lib/R/library/datasets/data/morley.tab
./embed-env/lib/R/library/grDevices/DESCRIPTION
./embed-env/lib/R/library/grDevices/INDEX
./embed-env/lib/R/library/grDevices/Meta/Rd.rds
./embed-env/lib/R/library/grDevices/Meta/demo.rds
./embed-env/lib/R/library/grDevices/Meta/features.rds
./embed-env/lib/R/library/grDevices/Meta/hsearch.rds
./embed-env/lib/R/library/grDevices/Meta/links.rds
./embed-env/lib/R/library/grDevices/Meta/nsInfo.rds
./embed-env/lib/R/library/grDevices/Meta/package.rds
./embed-env/lib/R/library/grDevices/NAMESPACE
./embed-env/lib/R/library/grDevices/R/grDevices
./embed-env/lib/R/library/grDevices/R/grDevices.rdb
./embed-env/lib/R/library/grDevices/R/grDevices.rdx
./embed-env/lib/R/library/grDevices/afm/ArialMT-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/ArialMT-BoldItalic.afm.gz
./embed-env/lib/R/library/grDevices/afm/ArialMT-Italic.afm.gz
./embed-env/lib/R/library/grDevices/afm/ArialMT.afm.gz
./embed-env/lib/R/library/grDevices/afm/CM_boldx_10.afm.gz
./embed-env/lib/R/library/grDevices/afm/CM_boldx_italic_10.afm.gz
./embed-env/lib/R/library/grDevices/afm/CM_italic_10.afm.gz
./embed-env/lib/R/library/grDevices/afm/CM_regular_10.afm.gz
./embed-env/lib/R/library/grDevices/afm/CM_symbol_10.afm.gz
./embed-env/lib/R/library/grDevices/afm/Courier-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/Courier-BoldOblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/Courier-Oblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/Courier.afm.gz
./embed-env/lib/R/library/grDevices/afm/Helvetica-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/Helvetica-BoldOblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/Helvetica-Oblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/Helvetica.afm.gz
./embed-env/lib/R/library/grDevices/afm/LICENSE.LPPL
./embed-env/lib/R/library/grDevices/afm/MustRead.html
./embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-BoldItalic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Italic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusMonoPS-Regular.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusRoman-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusRoman-BoldItalic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusRoman-Italic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusRoman-Regular.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-BoldItalic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-BoldOblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-Italic.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-Oblique.afm.gz
./embed-env/lib/R/library/grDevices/afm/NimbusSans-Regular.afm.gz
./embed-env/lib/R/library/grDevices/afm/README
./embed-env/lib/R/library/grDevices/afm/StandardSymbolsPS.afm.gz
./embed-env/lib/R/library/grDevices/afm/Symbol.afm.gz
./embed-env/lib/R/library/grDevices/afm/Times-Bold.afm.gz
./embed-env/lib/R/library/grDevices/afm/Times-BoldItalic.afm.gz
./embed-env/lib/R/library/grDevices/afm/Times-Italic.afm.gz
./embed-env/lib/R/library/grDevices/afm/Times-Roman.afm.gz
./embed-env/lib/R/library/grDevices/afm/ZapfDingbats.afm.gz
./embed-env/lib/R/library/grDevices/afm/a010013l.afm.gz
./embed-env/lib/R/library/grDevices/afm/a010015l.afm.gz
./embed-env/lib/R/library/grDevices/afm/a010033l.afm.gz
./embed-env/lib/R/library/grDevices/afm/a010035l.afm.gz
./embed-env/lib/R/library/grDevices/afm/agd_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/agdo____.afm.gz
./embed-env/lib/R/library/grDevices/afm/agw_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/agwo____.afm.gz
./embed-env/lib/R/library/grDevices/afm/b018012l.afm.gz
./embed-env/lib/R/library/grDevices/afm/b018015l.afm.gz
./embed-env/lib/R/library/grDevices/afm/b018032l.afm.gz
./embed-env/lib/R/library/grDevices/afm/b018035l.afm.gz
./embed-env/lib/R/library/grDevices/afm/bkd_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/bkdi____.afm.gz
./embed-env/lib/R/library/grDevices/afm/bkl_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/bkli____.afm.gz
./embed-env/lib/R/library/grDevices/afm/c059013l.afm.gz
./embed-env/lib/R/library/grDevices/afm/c059016l.afm.gz
./embed-env/lib/R/library/grDevices/afm/c059033l.afm.gz
./embed-env/lib/R/library/grDevices/afm/c059036l.afm.gz
./embed-env/lib/R/library/grDevices/afm/cmbxti10.afm.gz
./embed-env/lib/R/library/grDevices/afm/cmti10.afm.gz
./embed-env/lib/R/library/grDevices/afm/cob_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/cobo____.afm.gz
./embed-env/lib/R/library/grDevices/afm/com_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/coo_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hv______.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvb_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvbo____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvn_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvnb____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvnbo___.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvno____.afm.gz
./embed-env/lib/R/library/grDevices/afm/hvo_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019003l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019004l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019023l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019024l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019043l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019044l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019063l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n019064l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n021003l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n021004l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n021023l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n021024l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n022003l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n022004l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n022023l.afm.gz
./embed-env/lib/R/library/grDevices/afm/n022024l.afm.gz
./embed-env/lib/R/library/grDevices/afm/ncb_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/ncbi____.afm.gz
./embed-env/lib/R/library/grDevices/afm/nci_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/ncr_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/p052003l.afm.gz
./embed-env/lib/R/library/grDevices/afm/p052004l.afm.gz
./embed-env/lib/R/library/grDevices/afm/p052023l.afm.gz
./embed-env/lib/R/library/grDevices/afm/p052024l.afm.gz
./embed-env/lib/R/library/grDevices/afm/pob_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/pobi____.afm.gz
./embed-env/lib/R/library/grDevices/afm/poi_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/por_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/s050000l.afm.gz
./embed-env/lib/R/library/grDevices/afm/sy______.afm.gz
./embed-env/lib/R/library/grDevices/afm/tib_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/tibi____.afm.gz
./embed-env/lib/R/library/grDevices/afm/tii_____.afm.gz
./embed-env/lib/R/library/grDevices/afm/tir_____.afm.gz
./embed-env/lib/R/library/grDevices/demo/colors.R
./embed-env/lib/R/library/grDevices/demo/hclColors.R
./embed-env/lib/R/library/grDevices/enc/AdobeStd.enc
./embed-env/lib/R/library/grDevices/enc/AdobeSym.enc
./embed-env/lib/R/library/grDevices/enc/CP1250.enc
./embed-env/lib/R/library/grDevices/enc/CP1251.enc
./embed-env/lib/R/library/grDevices/enc/CP1253.enc
./embed-env/lib/R/library/grDevices/enc/CP1257.enc
./embed-env/lib/R/library/grDevices/enc/Cyrillic.enc
./embed-env/lib/R/library/grDevices/enc/Greek.enc
./embed-env/lib/R/library/grDevices/enc/ISOLatin1.enc
./embed-env/lib/R/library/grDevices/enc/ISOLatin2.enc
./embed-env/lib/R/library/grDevices/enc/ISOLatin7.enc
./embed-env/lib/R/library/grDevices/enc/ISOLatin9.enc
./embed-env/lib/R/library/grDevices/enc/KOI8-R.enc
./embed-env/lib/R/library/grDevices/enc/KOI8-U.enc
./embed-env/lib/R/library/grDevices/enc/PDFDoc.enc
./embed-env/lib/R/library/grDevices/enc/TeXtext.enc
./embed-env/lib/R/library/grDevices/enc/WinAnsi.enc
./embed-env/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
./embed-env/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-Medium.ttf
./embed-env/lib/R/library/grDevices/fonts/Roboto/LICENSE.txt
./embed-env/lib/R/library/grDevices/fonts/Roboto/Roboto-Medium.ttf
./embed-env/lib/R/library/grDevices/icc/srgb
./embed-env/lib/R/library/grDevices/icc/srgb.flate
./embed-env/lib/R/library/grDevices/libs/grDevices.so
./embed-env/lib/R/library/graphics/DESCRIPTION
./embed-env/lib/R/library/graphics/INDEX
./embed-env/lib/R/library/graphics/Meta/Rd.rds
./embed-env/lib/R/library/graphics/Meta/demo.rds
./embed-env/lib/R/library/graphics/Meta/features.rds
./embed-env/lib/R/library/graphics/Meta/hsearch.rds
./embed-env/lib/R/library/graphics/Meta/links.rds
./embed-env/lib/R/library/graphics/Meta/nsInfo.rds
./embed-env/lib/R/library/graphics/Meta/package.rds
./embed-env/lib/R/library/graphics/NAMESPACE
./embed-env/lib/R/library/graphics/R/graphics
./embed-env/lib/R/library/graphics/R/graphics.rdb
./embed-env/lib/R/library/graphics/R/graphics.rdx
./embed-env/lib/R/library/graphics/demo/Hershey.R
./embed-env/lib/R/library/graphics/demo/Japanese.R
./embed-env/lib/R/library/graphics/demo/graphics.R
./embed-env/lib/R/library/graphics/demo/image.R
./embed-env/lib/R/library/graphics/demo/persp.R
./embed-env/lib/R/library/graphics/demo/plotmath.R
./embed-env/lib/R/library/graphics/libs/graphics.so
./embed-env/lib/R/library/grid/DESCRIPTION
./embed-env/lib/R/library/grid/INDEX
./embed-env/lib/R/library/grid/Meta/Rd.rds
./embed-env/lib/R/library/grid/Meta/features.rds
./embed-env/lib/R/library/grid/Meta/hsearch.rds
./embed-env/lib/R/library/grid/Meta/links.rds
./embed-env/lib/R/library/grid/Meta/nsInfo.rds
./embed-env/lib/R/library/grid/Meta/package.rds
./embed-env/lib/R/library/grid/NAMESPACE
./embed-env/lib/R/library/grid/R/grid
./embed-env/lib/R/library/grid/R/grid.rdb
./embed-env/lib/R/library/grid/R/grid.rdx
./embed-env/lib/R/library/grid/doc/DivByZero.txt
./embed-env/lib/R/library/grid/doc/changes.txt
./embed-env/lib/R/library/grid/doc/displaylist.pdf
./embed-env/lib/R/library/grid/doc/frame.pdf
./embed-env/lib/R/library/grid/doc/grid.pdf
./embed-env/lib/R/library/grid/doc/grobs.pdf
./embed-env/lib/R/library/grid/doc/interactive.pdf
./embed-env/lib/R/library/grid/doc/locndimn.pdf
./embed-env/lib/R/library/grid/doc/moveline.pdf
./embed-env/lib/R/library/grid/doc/nonfinite.pdf
./embed-env/lib/R/library/grid/doc/plotexample.pdf
./embed-env/lib/R/library/grid/doc/rotated.pdf
./embed-env/lib/R/library/grid/doc/saveload.pdf
./embed-env/lib/R/library/grid/doc/sharing.pdf
./embed-env/lib/R/library/grid/doc/viewports.pdf
./embed-env/lib/R/library/grid/libs/grid.so
./embed-env/lib/R/library/methods/DESCRIPTION
./embed-env/lib/R/library/methods/INDEX
./embed-env/lib/R/library/methods/Meta/Rd.rds
./embed-env/lib/R/library/methods/Meta/features.rds
./embed-env/lib/R/library/methods/Meta/hsearch.rds
./embed-env/lib/R/library/methods/Meta/links.rds
./embed-env/lib/R/library/methods/Meta/nsInfo.rds
./embed-env/lib/R/library/methods/Meta/package.rds
./embed-env/lib/R/library/methods/NAMESPACE
./embed-env/lib/R/library/methods/R/methods
./embed-env/lib/R/library/methods/R/methods.rdb
./embed-env/lib/R/library/methods/R/methods.rdx
./embed-env/lib/R/library/methods/libs/methods.so
./embed-env/lib/R/library/parallel/DESCRIPTION
./embed-env/lib/R/library/parallel/INDEX
./embed-env/lib/R/library/parallel/Meta/Rd.rds
./embed-env/lib/R/library/parallel/Meta/features.rds
./embed-env/lib/R/library/parallel/Meta/hsearch.rds
./embed-env/lib/R/library/parallel/Meta/links.rds
./embed-env/lib/R/library/parallel/Meta/nsInfo.rds
./embed-env/lib/R/library/parallel/Meta/package.rds
./embed-env/lib/R/library/parallel/NAMESPACE
./embed-env/lib/R/library/parallel/R/parallel
./embed-env/lib/R/library/parallel/R/parallel.rdb
./embed-env/lib/R/library/parallel/R/parallel.rdx
./embed-env/lib/R/library/parallel/libs/parallel.so
./embed-env/lib/R/library/splines/DESCRIPTION
./embed-env/lib/R/library/splines/INDEX
./embed-env/lib/R/library/splines/Meta/Rd.rds
./embed-env/lib/R/library/splines/Meta/features.rds
./embed-env/lib/R/library/splines/Meta/hsearch.rds
./embed-env/lib/R/library/splines/Meta/links.rds
./embed-env/lib/R/library/splines/Meta/nsInfo.rds
./embed-env/lib/R/library/splines/Meta/package.rds
./embed-env/lib/R/library/splines/NAMESPACE
./embed-env/lib/R/library/splines/R/splines
./embed-env/lib/R/library/splines/R/splines.rdb
./embed-env/lib/R/library/splines/R/splines.rdx
./embed-env/lib/R/library/splines/libs/splines.so
./embed-env/lib/R/library/stats/COPYRIGHTS.modreg
./embed-env/lib/R/library/stats/DESCRIPTION
./embed-env/lib/R/library/stats/INDEX
./embed-env/lib/R/library/stats/Meta/Rd.rds
./embed-env/lib/R/library/stats/Meta/demo.rds
./embed-env/lib/R/library/stats/Meta/features.rds
./embed-env/lib/R/library/stats/Meta/hsearch.rds
./embed-env/lib/R/library/stats/Meta/links.rds
./embed-env/lib/R/library/stats/Meta/nsInfo.rds
./embed-env/lib/R/library/stats/Meta/package.rds
./embed-env/lib/R/library/stats/NAMESPACE
./embed-env/lib/R/library/stats/R/stats
./embed-env/lib/R/library/stats/R/stats.rdb
./embed-env/lib/R/library/stats/R/stats.rdx
./embed-env/lib/R/library/stats/SOURCES.ts
./embed-env/lib/R/library/stats/demo/glm.vr.R
./embed-env/lib/R/library/stats/demo/lm.glm.R
./embed-env/lib/R/library/stats/demo/nlm.R
./embed-env/lib/R/library/stats/demo/smooth.R
./embed-env/lib/R/library/stats/libs/stats.so
./embed-env/lib/R/library/stats4/DESCRIPTION
./embed-env/lib/R/library/stats4/INDEX
./embed-env/lib/R/library/stats4/Meta/Rd.rds
./embed-env/lib/R/library/stats4/Meta/features.rds
./embed-env/lib/R/library/stats4/Meta/hsearch.rds
./embed-env/lib/R/library/stats4/Meta/links.rds
./embed-env/lib/R/library/stats4/Meta/nsInfo.rds
./embed-env/lib/R/library/stats4/Meta/package.rds
./embed-env/lib/R/library/stats4/NAMESPACE
./embed-env/lib/R/library/stats4/R/stats4
./embed-env/lib/R/library/stats4/R/stats4.rdb
./embed-env/lib/R/library/stats4/R/stats4.rdx
./embed-env/lib/R/library/tcltk/DESCRIPTION
./embed-env/lib/R/library/tcltk/INDEX
./embed-env/lib/R/library/tcltk/Meta/Rd.rds
./embed-env/lib/R/library/tcltk/Meta/demo.rds
./embed-env/lib/R/library/tcltk/Meta/features.rds
./embed-env/lib/R/library/tcltk/Meta/hsearch.rds
./embed-env/lib/R/library/tcltk/Meta/links.rds
./embed-env/lib/R/library/tcltk/Meta/nsInfo.rds
./embed-env/lib/R/library/tcltk/Meta/package.rds
./embed-env/lib/R/library/tcltk/NAMESPACE
./embed-env/lib/R/library/tcltk/R/tcltk
./embed-env/lib/R/library/tcltk/demo/tkcanvas.R
./embed-env/lib/R/library/tcltk/demo/tkdensity.R
./embed-env/lib/R/library/tcltk/demo/tkfaq.R
./embed-env/lib/R/library/tcltk/demo/tkttest.R
./embed-env/lib/R/library/tcltk/exec/Tk-frontend.R
./embed-env/lib/R/library/tcltk/exec/console.tcl
./embed-env/lib/R/library/tcltk/exec/hierarchy.tcl
./embed-env/lib/R/library/tcltk/exec/pkgIndex.tcl
./embed-env/lib/R/library/tcltk/exec/progressbar.tcl
./embed-env/lib/R/library/tcltk/exec/util-dump.tcl
./embed-env/lib/R/library/tcltk/exec/util-expand.tcl
./embed-env/lib/R/library/tcltk/exec/util-number.tcl
./embed-env/lib/R/library/tcltk/exec/util-string.tcl
./embed-env/lib/R/library/tcltk/exec/util-tk.tcl
./embed-env/lib/R/library/tcltk/exec/util.tcl
./embed-env/lib/R/library/tcltk/exec/widget.tcl
./embed-env/lib/R/library/tools/DESCRIPTION
./embed-env/lib/R/library/tools/INDEX
./embed-env/lib/R/library/tools/Meta/Rd.rds
./embed-env/lib/R/library/tools/Meta/features.rds
./embed-env/lib/R/library/tools/Meta/hsearch.rds
./embed-env/lib/R/library/tools/Meta/links.rds
./embed-env/lib/R/library/tools/Meta/nsInfo.rds
./embed-env/lib/R/library/tools/Meta/package.rds
./embed-env/lib/R/library/tools/NAMESPACE
./embed-env/lib/R/library/tools/R/sysdata.rdb
./embed-env/lib/R/library/tools/R/sysdata.rdx
./embed-env/lib/R/library/tools/R/tools
./embed-env/lib/R/library/tools/R/tools.rdb
./embed-env/lib/R/library/tools/R/tools.rdx
./embed-env/lib/R/library/tools/libs/tools.so
./embed-env/lib/R/library/translations/DESCRIPTION
./embed-env/lib/R/library/utils/DESCRIPTION
./embed-env/lib/R/library/utils/INDEX
./embed-env/lib/R/library/utils/Meta/Rd.rds
./embed-env/lib/R/library/utils/Meta/features.rds
./embed-env/lib/R/library/utils/Meta/hsearch.rds
./embed-env/lib/R/library/utils/Meta/links.rds
./embed-env/lib/R/library/utils/Meta/nsInfo.rds
./embed-env/lib/R/library/utils/Meta/package.rds
./embed-env/lib/R/library/utils/NAMESPACE
./embed-env/lib/R/library/utils/R/sysdata.rdb
./embed-env/lib/R/library/utils/R/sysdata.rdx
./embed-env/lib/R/library/utils/R/utils
./embed-env/lib/R/library/utils/R/utils.rdb
./embed-env/lib/R/library/utils/R/utils.rdx
./embed-env/lib/R/library/utils/Sweave/Sweave-test-1.Rnw
./embed-env/lib/R/library/utils/Sweave/example-1.Rnw
./embed-env/lib/R/library/utils/doc/Sweave.pdf
./embed-env/lib/R/library/utils/iconvlist
./embed-env/lib/R/library/utils/libs/utils.so
./embed-env/lib/R/library/utils/misc/exDIF.csv
./embed-env/lib/R/library/utils/misc/exDIF.dif
./embed-env/lib/R/library/fastmap/DESCRIPTION
./embed-env/lib/R/library/fastmap/INDEX
./embed-env/lib/R/library/fastmap/LICENSE
./embed-env/lib/R/library/fastmap/Meta/Rd.rds
./embed-env/lib/R/library/fastmap/Meta/features.rds
./embed-env/lib/R/library/fastmap/Meta/hsearch.rds
./embed-env/lib/R/library/fastmap/Meta/links.rds
./embed-env/lib/R/library/fastmap/Meta/nsInfo.rds
./embed-env/lib/R/library/fastmap/Meta/package.rds
./embed-env/lib/R/library/fastmap/NAMESPACE
./embed-env/lib/R/library/fastmap/NEWS.md
./embed-env/lib/R/library/fastmap/R/fastmap
./embed-env/lib/R/library/fastmap/R/fastmap.rdb
./embed-env/lib/R/library/fastmap/R/fastmap.rdx
./embed-env/lib/R/library/fastmap/libs/fastmap.so
./embed-env/lib/R/library/digest/DESCRIPTION
./embed-env/lib/R/library/digest/GPL-2
./embed-env/lib/R/library/digest/INDEX
./embed-env/lib/R/library/digest/Meta/Rd.rds
./embed-env/lib/R/library/digest/Meta/demo.rds
./embed-env/lib/R/library/digest/Meta/features.rds
./embed-env/lib/R/library/digest/Meta/hsearch.rds
./embed-env/lib/R/library/digest/Meta/links.rds
./embed-env/lib/R/library/digest/Meta/nsInfo.rds
./embed-env/lib/R/library/digest/Meta/package.rds
./embed-env/lib/R/library/digest/Meta/vignette.rds
./embed-env/lib/R/library/digest/NAMESPACE
./embed-env/lib/R/library/digest/R/digest
./embed-env/lib/R/library/digest/R/digest.rdb
./embed-env/lib/R/library/digest/R/digest.rdx
./embed-env/lib/R/library/digest/demo/vectorised.R
./embed-env/lib/R/library/digest/doc/index.html
./embed-env/lib/R/library/digest/doc/sha1.R
./embed-env/lib/R/library/digest/doc/sha1.html
./embed-env/lib/R/library/digest/doc/sha1.md
./embed-env/lib/R/library/digest/include/pmurhashAPI.h
./embed-env/lib/R/library/digest/libs/digest.so
./embed-env/lib/R/library/digest/tinytest/test_aes.R
./embed-env/lib/R/library/digest/tinytest/test_blake3.R
./embed-env/lib/R/library/digest/tinytest/test_crc32.R
./embed-env/lib/R/library/digest/tinytest/test_digest.R
./embed-env/lib/R/library/digest/tinytest/test_digest2int.R
./embed-env/lib/R/library/digest/tinytest/test_encoding.R
./embed-env/lib/R/library/digest/tinytest/test_hmac.R
./embed-env/lib/R/library/digest/tinytest/test_misc.R
./embed-env/lib/R/library/digest/tinytest/test_new_matrix_behaviour.R
./embed-env/lib/R/library/digest/tinytest/test_num2hex.R
./embed-env/lib/R/library/digest/tinytest/test_raw.R
./embed-env/lib/R/library/digest/tinytest/test_sha1.R
./embed-env/lib/R/library/lattice/CITATION
./embed-env/lib/R/library/lattice/DESCRIPTION
./embed-env/lib/R/library/lattice/INDEX
./embed-env/lib/R/library/lattice/Meta/Rd.rds
./embed-env/lib/R/library/lattice/Meta/data.rds
./embed-env/lib/R/library/lattice/Meta/demo.rds
./embed-env/lib/R/library/lattice/Meta/features.rds
./embed-env/lib/R/library/lattice/Meta/hsearch.rds
./embed-env/lib/R/library/lattice/Meta/links.rds
./embed-env/lib/R/library/lattice/Meta/nsInfo.rds
./embed-env/lib/R/library/lattice/Meta/package.rds
./embed-env/lib/R/library/lattice/Meta/vignette.rds
./embed-env/lib/R/library/lattice/NAMESPACE
./embed-env/lib/R/library/lattice/NEWS.md
./embed-env/lib/R/library/lattice/R/lattice
./embed-env/lib/R/library/lattice/R/lattice.rdb
./embed-env/lib/R/library/lattice/R/lattice.rdx
./embed-env/lib/R/library/lattice/data/Rdata.rdb
./embed-env/lib/R/library/lattice/data/Rdata.rds
./embed-env/lib/R/library/lattice/data/Rdata.rdx
./embed-env/lib/R/library/lattice/demo/intervals.R
./embed-env/lib/R/library/lattice/demo/labels.R
./embed-env/lib/R/library/lattice/demo/lattice.R
./embed-env/lib/R/library/lattice/demo/panel.R
./embed-env/lib/R/library/lattice/doc/grid.R
./embed-env/lib/R/library/lattice/doc/grid.Rnw
./embed-env/lib/R/library/lattice/doc/grid.pdf
./embed-env/lib/R/library/lattice/doc/index.html
./embed-env/lib/R/library/lattice/libs/lattice.so
./embed-env/lib/R/library/lattice/po/de/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/lattice/po/en@quot/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/lattice/po/fr/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/lattice/po/it/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/lattice/po/ko/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/lattice/po/pl/LC_MESSAGES/R-lattice.mo
./embed-env/lib/R/library/magrittr/DESCRIPTION
./embed-env/lib/R/library/magrittr/INDEX
./embed-env/lib/R/library/magrittr/LICENSE
./embed-env/lib/R/library/magrittr/Meta/Rd.rds
./embed-env/lib/R/library/magrittr/Meta/features.rds
./embed-env/lib/R/library/magrittr/Meta/hsearch.rds
./embed-env/lib/R/library/magrittr/Meta/links.rds
./embed-env/lib/R/library/magrittr/Meta/nsInfo.rds
./embed-env/lib/R/library/magrittr/Meta/package.rds
./embed-env/lib/R/library/magrittr/Meta/vignette.rds
./embed-env/lib/R/library/magrittr/NAMESPACE
./embed-env/lib/R/library/magrittr/NEWS.md
./embed-env/lib/R/library/magrittr/R/magrittr
./embed-env/lib/R/library/magrittr/R/magrittr.rdb
./embed-env/lib/R/library/magrittr/R/magrittr.rdx
./embed-env/lib/R/library/magrittr/doc/index.html
./embed-env/lib/R/library/magrittr/doc/magrittr.R
./embed-env/lib/R/library/magrittr/doc/magrittr.Rmd
./embed-env/lib/R/library/magrittr/doc/magrittr.html
./embed-env/lib/R/library/magrittr/doc/tradeoffs.R
./embed-env/lib/R/library/magrittr/doc/tradeoffs.Rmd
./embed-env/lib/R/library/magrittr/doc/tradeoffs.html
./embed-env/lib/R/library/magrittr/help/AnIndex
./embed-env/lib/R/library/magrittr/help/aliases.rds
./embed-env/lib/R/library/magrittr/help/magrittr.rdb
./embed-env/lib/R/library/magrittr/help/magrittr.rdx
./embed-env/lib/R/library/magrittr/help/paths.rds
./embed-env/lib/R/library/magrittr/html/00Index.html
./embed-env/lib/R/library/magrittr/html/R.css
./embed-env/lib/R/library/magrittr/libs/magrittr.so
./embed-env/lib/R/library/magrittr/logo-hex.svg
./embed-env/lib/R/library/magrittr/logo.svg
./embed-env/lib/R/library/MASS/CITATION
./embed-env/lib/R/library/MASS/DESCRIPTION
./embed-env/lib/R/library/MASS/INDEX
./embed-env/lib/R/library/MASS/Meta/Rd.rds
./embed-env/lib/R/library/MASS/Meta/data.rds
./embed-env/lib/R/library/MASS/Meta/features.rds
./embed-env/lib/R/library/MASS/Meta/hsearch.rds
./embed-env/lib/R/library/MASS/Meta/links.rds
./embed-env/lib/R/library/MASS/Meta/nsInfo.rds
./embed-env/lib/R/library/MASS/Meta/package.rds
./embed-env/lib/R/library/MASS/NAMESPACE
./embed-env/lib/R/library/MASS/NEWS
./embed-env/lib/R/library/MASS/R/MASS
./embed-env/lib/R/library/MASS/R/MASS.rdb
./embed-env/lib/R/library/MASS/R/MASS.rdx
./embed-env/lib/R/library/MASS/data/Rdata.rdb
./embed-env/lib/R/library/MASS/data/Rdata.rds
./embed-env/lib/R/library/MASS/data/Rdata.rdx
./embed-env/lib/R/library/MASS/help/AnIndex
./embed-env/lib/R/library/MASS/help/MASS.rdb
./embed-env/lib/R/library/MASS/help/MASS.rdx
./embed-env/lib/R/library/MASS/help/aliases.rds
./embed-env/lib/R/library/MASS/help/paths.rds
./embed-env/lib/R/library/MASS/html/00Index.html
./embed-env/lib/R/library/MASS/html/R.css
./embed-env/lib/R/library/MASS/libs/MASS.so
./embed-env/lib/R/library/MASS/po/de/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/po/en@quot/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/po/fr/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/po/it/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/po/ko/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/po/pl/LC_MESSAGES/R-MASS.mo
./embed-env/lib/R/library/MASS/scripts/ch01.R
./embed-env/lib/R/library/MASS/scripts/ch02.R
./embed-env/lib/R/library/MASS/scripts/ch03.R
./embed-env/lib/R/library/MASS/scripts/ch04.R
./embed-env/lib/R/library/MASS/scripts/ch05.R
./embed-env/lib/R/library/MASS/scripts/ch06.R
./embed-env/lib/R/library/MASS/scripts/ch07.R
./embed-env/lib/R/library/MASS/scripts/ch08.R
./embed-env/lib/R/library/MASS/scripts/ch09.R
./embed-env/lib/R/library/MASS/scripts/ch10.R
./embed-env/lib/R/library/MASS/scripts/ch11.R
./embed-env/lib/R/library/MASS/scripts/ch12.R
./embed-env/lib/R/library/MASS/scripts/ch13.R
./embed-env/lib/R/library/MASS/scripts/ch14.R
./embed-env/lib/R/library/MASS/scripts/ch15.R
./embed-env/lib/R/library/MASS/scripts/ch16.R
./embed-env/lib/R/library/isoband/DESCRIPTION
./embed-env/lib/R/library/isoband/INDEX
./embed-env/lib/R/library/isoband/LICENSE
./embed-env/lib/R/library/isoband/Meta/Rd.rds
./embed-env/lib/R/library/isoband/Meta/features.rds
./embed-env/lib/R/library/isoband/Meta/hsearch.rds
./embed-env/lib/R/library/isoband/Meta/links.rds
./embed-env/lib/R/library/isoband/Meta/nsInfo.rds
./embed-env/lib/R/library/isoband/Meta/package.rds
./embed-env/lib/R/library/isoband/Meta/vignette.rds
./embed-env/lib/R/library/isoband/NAMESPACE
./embed-env/lib/R/library/isoband/NEWS.md
./embed-env/lib/R/library/isoband/R/isoband
./embed-env/lib/R/library/isoband/R/isoband.rdb
./embed-env/lib/R/library/isoband/R/isoband.rdx
./embed-env/lib/R/library/isoband/doc/index.html
./embed-env/lib/R/library/isoband/doc/isoband1.R
./embed-env/lib/R/library/isoband/doc/isoband1.Rmd
./embed-env/lib/R/library/isoband/doc/isoband1.html
./embed-env/lib/R/library/isoband/doc/isoband3.R
./embed-env/lib/R/library/isoband/doc/isoband3.Rmd
./embed-env/lib/R/library/isoband/doc/isoband3.html
./embed-env/lib/R/library/isoband/help/AnIndex
./embed-env/lib/R/library/isoband/help/aliases.rds
./embed-env/lib/R/library/isoband/help/isoband.rdb
./embed-env/lib/R/library/isoband/help/isoband.rdx
./embed-env/lib/R/library/isoband/help/paths.rds
./embed-env/lib/R/library/isoband/html/00Index.html
./embed-env/lib/R/library/isoband/html/R.css
./embed-env/lib/R/library/isoband/libs/isoband.so
./embed-env/lib/R/library/utf8/DESCRIPTION
./embed-env/lib/R/library/utf8/INDEX
./embed-env/lib/R/library/utf8/LICENSE
./embed-env/lib/R/library/utf8/Meta/Rd.rds
./embed-env/lib/R/library/utf8/Meta/features.rds
./embed-env/lib/R/library/utf8/Meta/hsearch.rds
./embed-env/lib/R/library/utf8/Meta/links.rds
./embed-env/lib/R/library/utf8/Meta/nsInfo.rds
./embed-env/lib/R/library/utf8/Meta/package.rds
./embed-env/lib/R/library/utf8/Meta/vignette.rds
./embed-env/lib/R/library/utf8/NAMESPACE
./embed-env/lib/R/library/utf8/R/utf8
./embed-env/lib/R/library/utf8/R/utf8.rdb
./embed-env/lib/R/library/utf8/R/utf8.rdx
./embed-env/lib/R/library/utf8/doc/index.html
./embed-env/lib/R/library/utf8/doc/utf8.Rmd
./embed-env/lib/R/library/utf8/doc/utf8.html
./embed-env/lib/R/library/utf8/help/AnIndex
./embed-env/lib/R/library/utf8/help/aliases.rds
./embed-env/lib/R/library/utf8/help/paths.rds
./embed-env/lib/R/library/utf8/help/utf8.rdb
./embed-env/lib/R/library/utf8/help/utf8.rdx
./embed-env/lib/R/library/utf8/html/00Index.html
./embed-env/lib/R/library/utf8/html/R.css
./embed-env/lib/R/library/utf8/libs/utf8.so
./embed-env/lib/R/library/fansi/DESCRIPTION
./embed-env/lib/R/library/fansi/INDEX
./embed-env/lib/R/library/fansi/Meta/Rd.rds
./embed-env/lib/R/library/fansi/Meta/features.rds
./embed-env/lib/R/library/fansi/Meta/hsearch.rds
./embed-env/lib/R/library/fansi/Meta/links.rds
./embed-env/lib/R/library/fansi/Meta/nsInfo.rds
./embed-env/lib/R/library/fansi/Meta/package.rds
./embed-env/lib/R/library/fansi/Meta/vignette.rds
./embed-env/lib/R/library/fansi/NAMESPACE
./embed-env/lib/R/library/fansi/NEWS.md
./embed-env/lib/R/library/fansi/R/fansi
./embed-env/lib/R/library/fansi/R/fansi.rdb
./embed-env/lib/R/library/fansi/R/fansi.rdx
./embed-env/lib/R/library/fansi/doc/index.html
./embed-env/lib/R/library/fansi/doc/sgr-in-rmd.R
./embed-env/lib/R/library/fansi/doc/sgr-in-rmd.Rmd
./embed-env/lib/R/library/fansi/doc/sgr-in-rmd.html
./embed-env/lib/R/library/fansi/help/AnIndex
./embed-env/lib/R/library/fansi/help/aliases.rds
./embed-env/lib/R/library/fansi/help/fansi.rdb
./embed-env/lib/R/library/fansi/help/fansi.rdx
./embed-env/lib/R/library/fansi/help/paths.rds
./embed-env/lib/R/library/fansi/html/00Index.html
./embed-env/lib/R/library/fansi/html/R.css
./embed-env/lib/R/library/fansi/libs/fansi.so
./embed-env/lib/R/library/base64enc/DESCRIPTION
./embed-env/lib/R/library/base64enc/INDEX
./embed-env/lib/R/library/base64enc/Meta/Rd.rds
./embed-env/lib/R/library/base64enc/Meta/features.rds
./embed-env/lib/R/library/base64enc/Meta/hsearch.rds
./embed-env/lib/R/library/base64enc/Meta/links.rds
./embed-env/lib/R/library/base64enc/Meta/nsInfo.rds
./embed-env/lib/R/library/base64enc/Meta/package.rds
./embed-env/lib/R/library/base64enc/NAMESPACE
./embed-env/lib/R/library/base64enc/NEWS
./embed-env/lib/R/library/base64enc/R/base64enc
./embed-env/lib/R/library/base64enc/R/base64enc.rdb
./embed-env/lib/R/library/base64enc/R/base64enc.rdx
./embed-env/lib/R/library/base64enc/help/AnIndex
./embed-env/lib/R/library/base64enc/help/aliases.rds
./embed-env/lib/R/library/base64enc/help/base64enc.rdb
./embed-env/lib/R/library/base64enc/help/base64enc.rdx
./embed-env/lib/R/library/base64enc/help/paths.rds
./embed-env/lib/R/library/base64enc/html/00Index.html
./embed-env/lib/R/library/base64enc/html/R.css
./embed-env/lib/R/library/base64enc/libs/base64enc.so
./embed-env/lib/R/library/farver/DESCRIPTION
./embed-env/lib/R/library/farver/INDEX
./embed-env/lib/R/library/farver/LICENSE
./embed-env/lib/R/library/farver/Meta/Rd.rds
./embed-env/lib/R/library/farver/Meta/features.rds
./embed-env/lib/R/library/farver/Meta/hsearch.rds
./embed-env/lib/R/library/farver/Meta/links.rds
./embed-env/lib/R/library/farver/Meta/nsInfo.rds
./embed-env/lib/R/library/farver/Meta/package.rds
./embed-env/lib/R/library/farver/NAMESPACE
./embed-env/lib/R/library/farver/NEWS.md
./embed-env/lib/R/library/farver/R/farver
./embed-env/lib/R/library/farver/R/farver.rdb
./embed-env/lib/R/library/farver/R/farver.rdx
./embed-env/lib/R/library/farver/R/sysdata.rdb
./embed-env/lib/R/library/farver/R/sysdata.rdx
./embed-env/lib/R/library/farver/help/AnIndex
./embed-env/lib/R/library/farver/help/aliases.rds
./embed-env/lib/R/library/farver/help/farver.rdb
./embed-env/lib/R/library/farver/help/farver.rdx
./embed-env/lib/R/library/farver/help/figures/logo.svg
./embed-env/lib/R/library/farver/help/paths.rds
./embed-env/lib/R/library/farver/html/00Index.html
./embed-env/lib/R/library/farver/html/R.css
./embed-env/lib/R/library/farver/libs/farver.so
./embed-env/lib/R/library/colorspace/CITATION
./embed-env/lib/R/library/colorspace/DESCRIPTION
./embed-env/lib/R/library/colorspace/INDEX
./embed-env/lib/R/library/colorspace/LICENSE
./embed-env/lib/R/library/colorspace/Meta/Rd.rds
./embed-env/lib/R/library/colorspace/Meta/data.rds
./embed-env/lib/R/library/colorspace/Meta/demo.rds
./embed-env/lib/R/library/colorspace/Meta/features.rds
./embed-env/lib/R/library/colorspace/Meta/hsearch.rds
./embed-env/lib/R/library/colorspace/Meta/links.rds
./embed-env/lib/R/library/colorspace/Meta/nsInfo.rds
./embed-env/lib/R/library/colorspace/Meta/package.rds
./embed-env/lib/R/library/colorspace/Meta/vignette.rds
./embed-env/lib/R/library/colorspace/NAMESPACE
./embed-env/lib/R/library/colorspace/NEWS.md
./embed-env/lib/R/library/colorspace/R/colorspace
./embed-env/lib/R/library/colorspace/R/colorspace.rdb
./embed-env/lib/R/library/colorspace/R/colorspace.rdx
./embed-env/lib/R/library/colorspace/cvdemulator/html/appInfo.html
./embed-env/lib/R/library/colorspace/cvdemulator/html/info.html
./embed-env/lib/R/library/colorspace/cvdemulator/prepareStaticContent.R
./embed-env/lib/R/library/colorspace/cvdemulator/server.R
./embed-env/lib/R/library/colorspace/cvdemulator/ui.R
./embed-env/lib/R/library/colorspace/cvdemulator/www/cvdemulator.css
./embed-env/lib/R/library/colorspace/cvdemulator/www/cvdemulator_darkmode.css
./embed-env/lib/R/library/colorspace/data/Rdata.rdb
./embed-env/lib/R/library/colorspace/data/Rdata.rds
./embed-env/lib/R/library/colorspace/data/Rdata.rdx
./embed-env/lib/R/library/colorspace/demo/brewer.R
./embed-env/lib/R/library/colorspace/demo/carto.R
./embed-env/lib/R/library/colorspace/demo/scico.R
./embed-env/lib/R/library/colorspace/demo/viridis.R
./embed-env/lib/R/library/colorspace/doc/colorspace.R
./embed-env/lib/R/library/colorspace/doc/colorspace.Rmd
./embed-env/lib/R/library/colorspace/doc/colorspace.html
./embed-env/lib/R/library/colorspace/doc/hcl-colors.R
./embed-env/lib/R/library/colorspace/doc/hcl-colors.Rnw
./embed-env/lib/R/library/colorspace/doc/hcl-colors.pdf
./embed-env/lib/R/library/colorspace/doc/index.html
./embed-env/lib/R/library/colorspace/hclcolorpicker/html/info.html
./embed-env/lib/R/library/colorspace/hclcolorpicker/prepareStaticContent.R
./embed-env/lib/R/library/colorspace/hclcolorpicker/server.R
./embed-env/lib/R/library/colorspace/hclcolorpicker/ui.R
./embed-env/lib/R/library/colorspace/hclcolorpicker/www/hclcolorpicker.css
./embed-env/lib/R/library/colorspace/hclcolorpicker/www/hclcolorpicker_darkmode.css
./embed-env/lib/R/library/colorspace/hclwizard/html/GrADS.html
./embed-env/lib/R/library/colorspace/hclwizard/html/R.html
./embed-env/lib/R/library/colorspace/hclwizard/html/RReg.html
./embed-env/lib/R/library/colorspace/hclwizard/html/Register.html
./embed-env/lib/R/library/colorspace/hclwizard/html/RegisterRcode.html
./embed-env/lib/R/library/colorspace/hclwizard/html/colorplane.html
./embed-env/lib/R/library/colorspace/hclwizard/html/info.html
./embed-env/lib/R/library/colorspace/hclwizard/html/matlab.html
./embed-env/lib/R/library/colorspace/hclwizard/html/python.html
./embed-env/lib/R/library/colorspace/hclwizard/prepareStaticContent.R
./embed-env/lib/R/library/colorspace/hclwizard/server.R
./embed-env/lib/R/library/colorspace/hclwizard/ui.R
./embed-env/lib/R/library/colorspace/hclwizard/www/hclwizard.css
./embed-env/lib/R/library/colorspace/hclwizard/www/hclwizard_darkmode.css
./embed-env/lib/R/library/colorspace/help/AnIndex
./embed-env/lib/R/library/colorspace/help/aliases.rds
./embed-env/lib/R/library/colorspace/help/colorspace.rdb
./embed-env/lib/R/library/colorspace/help/colorspace.rdx
./embed-env/lib/R/library/colorspace/help/paths.rds
./embed-env/lib/R/library/colorspace/html/00Index.html
./embed-env/lib/R/library/colorspace/html/R.css
./embed-env/lib/R/library/colorspace/libs/colorspace.so
./embed-env/lib/R/library/cli/DESCRIPTION
./embed-env/lib/R/library/cli/INDEX
./embed-env/lib/R/library/cli/LICENSE
./embed-env/lib/R/library/cli/Meta/Rd.rds
./embed-env/lib/R/library/cli/Meta/features.rds
./embed-env/lib/R/library/cli/Meta/hsearch.rds
./embed-env/lib/R/library/cli/Meta/links.rds
./embed-env/lib/R/library/cli/Meta/nsInfo.rds
./embed-env/lib/R/library/cli/Meta/package.rds
./embed-env/lib/R/library/cli/NAMESPACE
./embed-env/lib/R/library/cli/NEWS.md
./embed-env/lib/R/library/cli/R/cli
./embed-env/lib/R/library/cli/R/cli.rdb
./embed-env/lib/R/library/cli/R/cli.rdx
./embed-env/lib/R/library/cli/R/sysdata.rdb
./embed-env/lib/R/library/cli/R/sysdata.rdx
./embed-env/lib/R/library/cli/examples/apps/news.R
./embed-env/lib/R/library/cli/examples/apps/outdated.R
./embed-env/lib/R/library/cli/examples/apps/search.R
./embed-env/lib/R/library/cli/examples/apps/up.R
./embed-env/lib/R/library/cli/exec/news.R
./embed-env/lib/R/library/cli/exec/outdated.R
./embed-env/lib/R/library/cli/exec/search.R
./embed-env/lib/R/library/cli/exec/up.R
./embed-env/lib/R/library/cli/help/AnIndex
./embed-env/lib/R/library/cli/help/aliases.rds
./embed-env/lib/R/library/cli/help/cli.rdb
./embed-env/lib/R/library/cli/help/cli.rdx
./embed-env/lib/R/library/cli/help/figures/demo-spinners.svg
./embed-env/lib/R/library/cli/help/figures/get-spinner.svg
./embed-env/lib/R/library/cli/help/figures/make-spinner-custom.svg
./embed-env/lib/R/library/cli/help/figures/make-spinner-default.svg
./embed-env/lib/R/library/cli/help/figures/make-spinner-template.svg
./embed-env/lib/R/library/cli/help/figures/progress-1.svg
./embed-env/lib/R/library/cli/help/figures/progress-after.svg
./embed-env/lib/R/library/cli/help/figures/progress-along-1.svg
./embed-env/lib/R/library/cli/help/figures/progress-along-2.svg
./embed-env/lib/R/library/cli/help/figures/progress-along-3.svg
./embed-env/lib/R/library/cli/help/figures/progress-clear.svg
./embed-env/lib/R/library/cli/help/figures/progress-current.svg
./embed-env/lib/R/library/cli/help/figures/progress-format.svg
./embed-env/lib/R/library/cli/help/figures/progress-message.svg
./embed-env/lib/R/library/cli/help/figures/progress-natotal.svg
./embed-env/lib/R/library/cli/help/figures/progress-output.svg
./embed-env/lib/R/library/cli/help/figures/progress-output2.svg
./embed-env/lib/R/library/cli/help/figures/progress-step-dynamic.svg
./embed-env/lib/R/library/cli/help/figures/progress-step-msg.svg
./embed-env/lib/R/library/cli/help/figures/progress-step-spin.svg
./embed-env/lib/R/library/cli/help/figures/progress-step.svg
./embed-env/lib/R/library/cli/help/figures/progress-tasks.svg
./embed-env/lib/R/library/cli/help/paths.rds
./embed-env/lib/R/library/cli/html/00Index.html
./embed-env/lib/R/library/cli/html/R.css
./embed-env/lib/R/library/cli/include/cli/progress.h
./embed-env/lib/R/library/cli/libs/cli.so
./embed-env/lib/R/library/cli/logo.txt
./embed-env/lib/R/library/cli/shiny/along/app.R
./embed-env/lib/R/library/cli/shiny/format/app.R
./embed-env/lib/R/library/cli/shiny/nested/app.R
./embed-env/lib/R/library/cli/shiny/output/app.R
./embed-env/lib/R/library/cli/shiny/simple/app.R
./embed-env/lib/R/library/glue/DESCRIPTION
./embed-env/lib/R/library/glue/INDEX
./embed-env/lib/R/library/glue/LICENSE
./embed-env/lib/R/library/glue/Meta/Rd.rds
./embed-env/lib/R/library/glue/Meta/features.rds
./embed-env/lib/R/library/glue/Meta/hsearch.rds
./embed-env/lib/R/library/glue/Meta/links.rds
./embed-env/lib/R/library/glue/Meta/nsInfo.rds
./embed-env/lib/R/library/glue/Meta/package.rds
./embed-env/lib/R/library/glue/Meta/vignette.rds
./embed-env/lib/R/library/glue/NAMESPACE
./embed-env/lib/R/library/glue/NEWS.md
./embed-env/lib/R/library/glue/R/glue
./embed-env/lib/R/library/glue/R/glue.rdb
./embed-env/lib/R/library/glue/R/glue.rdx
./embed-env/lib/R/library/glue/doc/engines.R
./embed-env/lib/R/library/glue/doc/engines.Rmd
./embed-env/lib/R/library/glue/doc/engines.html
./embed-env/lib/R/library/glue/doc/index.html
./embed-env/lib/R/library/glue/doc/transformers.R
./embed-env/lib/R/library/glue/doc/transformers.Rmd
./embed-env/lib/R/library/glue/doc/transformers.html
./embed-env/lib/R/library/glue/help/AnIndex
./embed-env/lib/R/library/glue/help/aliases.rds
./embed-env/lib/R/library/glue/help/glue.rdb
./embed-env/lib/R/library/glue/help/glue.rdx
./embed-env/lib/R/library/glue/help/paths.rds
./embed-env/lib/R/library/glue/html/00Index.html
./embed-env/lib/R/library/glue/html/R.css
./embed-env/lib/R/library/glue/libs/glue.so
./embed-env/lib/R/library/jsonlite/CITATION
./embed-env/lib/R/library/jsonlite/DESCRIPTION
./embed-env/lib/R/library/jsonlite/INDEX
./embed-env/lib/R/library/jsonlite/LICENSE
./embed-env/lib/R/library/jsonlite/Meta/Rd.rds
./embed-env/lib/R/library/jsonlite/Meta/features.rds
./embed-env/lib/R/library/jsonlite/Meta/hsearch.rds
./embed-env/lib/R/library/jsonlite/Meta/links.rds
./embed-env/lib/R/library/jsonlite/Meta/nsInfo.rds
./embed-env/lib/R/library/jsonlite/Meta/package.rds
./embed-env/lib/R/library/jsonlite/Meta/vignette.rds
./embed-env/lib/R/library/jsonlite/NAMESPACE
./embed-env/lib/R/library/jsonlite/NEWS
./embed-env/lib/R/library/jsonlite/R/jsonlite
./embed-env/lib/R/library/jsonlite/R/jsonlite.rdb
./embed-env/lib/R/library/jsonlite/R/jsonlite.rdx
./embed-env/lib/R/library/jsonlite/doc/index.html
./embed-env/lib/R/library/jsonlite/doc/json-aaquickstart.R
./embed-env/lib/R/library/jsonlite/doc/json-aaquickstart.Rmd
./embed-env/lib/R/library/jsonlite/doc/json-aaquickstart.html
./embed-env/lib/R/library/jsonlite/doc/json-apis.Rmd
./embed-env/lib/R/library/jsonlite/doc/json-apis.html
./embed-env/lib/R/library/jsonlite/doc/json-mapping.pdf
./embed-env/lib/R/library/jsonlite/doc/json-mapping.pdf.asis
./embed-env/lib/R/library/jsonlite/doc/json-opencpu.pdf
./embed-env/lib/R/library/jsonlite/doc/json-opencpu.pdf.asis
./embed-env/lib/R/library/jsonlite/doc/json-paging.Rmd
./embed-env/lib/R/library/jsonlite/doc/json-paging.html
./embed-env/lib/R/library/jsonlite/help/AnIndex
./embed-env/lib/R/library/jsonlite/help/aliases.rds
./embed-env/lib/R/library/jsonlite/help/jsonlite.rdb
./embed-env/lib/R/library/jsonlite/help/jsonlite.rdx
./embed-env/lib/R/library/jsonlite/help/paths.rds
./embed-env/lib/R/library/jsonlite/html/00Index.html
./embed-env/lib/R/library/jsonlite/html/R.css
./embed-env/lib/R/library/jsonlite/libs/jsonlite.so
./embed-env/lib/R/library/rlang/DESCRIPTION
./embed-env/lib/R/library/rlang/INDEX
./embed-env/lib/R/library/rlang/LICENSE
./embed-env/lib/R/library/rlang/Meta/Rd.rds
./embed-env/lib/R/library/rlang/Meta/features.rds
./embed-env/lib/R/library/rlang/Meta/hsearch.rds
./embed-env/lib/R/library/rlang/Meta/links.rds
./embed-env/lib/R/library/rlang/Meta/nsInfo.rds
./embed-env/lib/R/library/rlang/Meta/package.rds
./embed-env/lib/R/library/rlang/NAMESPACE
./embed-env/lib/R/library/rlang/NEWS.md
./embed-env/lib/R/library/rlang/R/rlang
./embed-env/lib/R/library/rlang/R/rlang.rdb
./embed-env/lib/R/library/rlang/R/rlang.rdx
./embed-env/lib/R/library/rlang/backtrace-ver
./embed-env/lib/R/library/rlang/help/AnIndex
./embed-env/lib/R/library/rlang/help/aliases.rds
./embed-env/lib/R/library/rlang/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-retired.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/rlang/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/rlang/help/paths.rds
./embed-env/lib/R/library/rlang/help/rlang.rdb
./embed-env/lib/R/library/rlang/help/rlang.rdx
./embed-env/lib/R/library/rlang/html/00Index.html
./embed-env/lib/R/library/rlang/html/R.css
./embed-env/lib/R/library/rlang/libs/rlang.so
./embed-env/lib/R/library/nlme/CITATION
./embed-env/lib/R/library/nlme/DESCRIPTION
./embed-env/lib/R/library/nlme/INDEX
./embed-env/lib/R/library/nlme/Meta/Rd.rds
./embed-env/lib/R/library/nlme/Meta/data.rds
./embed-env/lib/R/library/nlme/Meta/features.rds
./embed-env/lib/R/library/nlme/Meta/hsearch.rds
./embed-env/lib/R/library/nlme/Meta/links.rds
./embed-env/lib/R/library/nlme/Meta/nsInfo.rds
./embed-env/lib/R/library/nlme/Meta/package.rds
./embed-env/lib/R/library/nlme/NAMESPACE
./embed-env/lib/R/library/nlme/R/nlme
./embed-env/lib/R/library/nlme/R/nlme.rdb
./embed-env/lib/R/library/nlme/R/nlme.rdx
./embed-env/lib/R/library/nlme/data/Rdata.rdb
./embed-env/lib/R/library/nlme/data/Rdata.rds
./embed-env/lib/R/library/nlme/data/Rdata.rdx
./embed-env/lib/R/library/nlme/help/AnIndex
./embed-env/lib/R/library/nlme/help/aliases.rds
./embed-env/lib/R/library/nlme/help/nlme.rdb
./embed-env/lib/R/library/nlme/help/nlme.rdx
./embed-env/lib/R/library/nlme/help/paths.rds
./embed-env/lib/R/library/nlme/html/00Index.html
./embed-env/lib/R/library/nlme/html/R.css
./embed-env/lib/R/library/nlme/libs/nlme.so
./embed-env/lib/R/library/nlme/mlbook/README
./embed-env/lib/R/library/nlme/mlbook/ch04.R
./embed-env/lib/R/library/nlme/mlbook/ch05.R
./embed-env/lib/R/library/nlme/po/de/LC_MESSAGES/R-nlme.mo
./embed-env/lib/R/library/nlme/po/de/LC_MESSAGES/nlme.mo
./embed-env/lib/R/library/nlme/po/en@quot/LC_MESSAGES/R-nlme.mo
./embed-env/lib/R/library/nlme/po/en@quot/LC_MESSAGES/nlme.mo
./embed-env/lib/R/library/nlme/po/fr/LC_MESSAGES/R-nlme.mo
./embed-env/lib/R/library/nlme/po/fr/LC_MESSAGES/nlme.mo
./embed-env/lib/R/library/nlme/po/ko/LC_MESSAGES/R-nlme.mo
./embed-env/lib/R/library/nlme/po/ko/LC_MESSAGES/nlme.mo
./embed-env/lib/R/library/nlme/po/pl/LC_MESSAGES/R-nlme.mo
./embed-env/lib/R/library/nlme/po/pl/LC_MESSAGES/nlme.mo
./embed-env/lib/R/library/nlme/scripts/ch01.R
./embed-env/lib/R/library/nlme/scripts/ch02.R
./embed-env/lib/R/library/nlme/scripts/ch03.R
./embed-env/lib/R/library/nlme/scripts/ch04.R
./embed-env/lib/R/library/nlme/scripts/ch05.R
./embed-env/lib/R/library/nlme/scripts/ch06.R
./embed-env/lib/R/library/nlme/scripts/ch08.R
./embed-env/lib/R/library/nlme/scripts/runme.R
./embed-env/lib/R/library/nlme/scripts/sims.rda
./embed-env/lib/R/library/Matrix/DESCRIPTION
./embed-env/lib/R/library/Matrix/INDEX
./embed-env/lib/R/library/Matrix/LICENCE
./embed-env/lib/R/library/Matrix/Meta/Rd.rds
./embed-env/lib/R/library/Matrix/Meta/data.rds
./embed-env/lib/R/library/Matrix/Meta/features.rds
./embed-env/lib/R/library/Matrix/Meta/hsearch.rds
./embed-env/lib/R/library/Matrix/Meta/links.rds
./embed-env/lib/R/library/Matrix/Meta/nsInfo.rds
./embed-env/lib/R/library/Matrix/Meta/package.rds
./embed-env/lib/R/library/Matrix/Meta/vignette.rds
./embed-env/lib/R/library/Matrix/NAMESPACE
./embed-env/lib/R/library/Matrix/NEWS.Rd
./embed-env/lib/R/library/Matrix/R/Matrix
./embed-env/lib/R/library/Matrix/R/Matrix.rdb
./embed-env/lib/R/library/Matrix/R/Matrix.rdx
./embed-env/lib/R/library/Matrix/data/CAex.R
./embed-env/lib/R/library/Matrix/data/KNex.R
./embed-env/lib/R/library/Matrix/data/USCounties.R
./embed-env/lib/R/library/Matrix/data/datalist
./embed-env/lib/R/library/Matrix/data/wrld_1deg.R
./embed-env/lib/R/library/Matrix/doc/Comparisons.R
./embed-env/lib/R/library/Matrix/doc/Comparisons.Rnw
./embed-env/lib/R/library/Matrix/doc/Comparisons.pdf
./embed-env/lib/R/library/Matrix/doc/Design-issues.R
./embed-env/lib/R/library/Matrix/doc/Design-issues.Rnw
./embed-env/lib/R/library/Matrix/doc/Design-issues.pdf
./embed-env/lib/R/library/Matrix/doc/Intro2Matrix.R
./embed-env/lib/R/library/Matrix/doc/Intro2Matrix.Rnw
./embed-env/lib/R/library/Matrix/doc/Intro2Matrix.pdf
./embed-env/lib/R/library/Matrix/doc/Introduction.R
./embed-env/lib/R/library/Matrix/doc/Introduction.Rnw
./embed-env/lib/R/library/Matrix/doc/Introduction.pdf
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/AMD/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/AMD/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/AMD/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CAMD/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CAMD/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CAMD/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CCOLAMD/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/Changelog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/LICENSE.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CHOLMOD/SuiteSparse_metis/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/COLAMD/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/Doc/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/Doc/License.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/CXSparse/README.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/ChangeLog
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/LICENSE.txt
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/README.md
./embed-env/lib/R/library/Matrix/doc/SuiteSparse/SuiteSparse_config/README.txt
./embed-env/lib/R/library/Matrix/doc/index.html
./embed-env/lib/R/library/Matrix/doc/sparseModels.R
./embed-env/lib/R/library/Matrix/doc/sparseModels.Rnw
./embed-env/lib/R/library/Matrix/doc/sparseModels.pdf
./embed-env/lib/R/library/Matrix/external/CAex_slots.rda
./embed-env/lib/R/library/Matrix/external/KNex_slots.rda
./embed-env/lib/R/library/Matrix/external/USCounties_slots.rda
./embed-env/lib/R/library/Matrix/external/Z_NA_rnk.rds
./embed-env/lib/R/library/Matrix/external/jgl009.mtx
./embed-env/lib/R/library/Matrix/external/lund_a.mtx
./embed-env/lib/R/library/Matrix/external/lund_a.rsa
./embed-env/lib/R/library/Matrix/external/pores_1.mtx
./embed-env/lib/R/library/Matrix/external/symA.rda
./embed-env/lib/R/library/Matrix/external/symW.rda
./embed-env/lib/R/library/Matrix/external/test3comp.rda
./embed-env/lib/R/library/Matrix/external/utm300.rua
./embed-env/lib/R/library/Matrix/external/wrld_1deg_slots.rda
./embed-env/lib/R/library/Matrix/external/wrong.mtx
./embed-env/lib/R/library/Matrix/help/AnIndex
./embed-env/lib/R/library/Matrix/help/Matrix.rdb
./embed-env/lib/R/library/Matrix/help/Matrix.rdx
./embed-env/lib/R/library/Matrix/help/aliases.rds
./embed-env/lib/R/library/Matrix/help/macros/local.Rd
./embed-env/lib/R/library/Matrix/help/paths.rds
./embed-env/lib/R/library/Matrix/html/00Index.html
./embed-env/lib/R/library/Matrix/html/R.css
./embed-env/lib/R/library/Matrix/include/Matrix/Matrix.h
./embed-env/lib/R/library/Matrix/include/Matrix/alloca.h
./embed-env/lib/R/library/Matrix/include/Matrix/cholmod-utils.h
./embed-env/lib/R/library/Matrix/include/Matrix/cholmod.h
./embed-env/lib/R/library/Matrix/include/Matrix/remap.h
./embed-env/lib/R/library/Matrix/include/Matrix/stubs.c
./embed-env/lib/R/library/Matrix/include/Matrix/version.h
./embed-env/lib/R/library/Matrix/include/Matrix.h
./embed-env/lib/R/library/Matrix/include/Matrix_stubs.c
./embed-env/lib/R/library/Matrix/include/cholmod.h
./embed-env/lib/R/library/Matrix/libs/Matrix.so
./embed-env/lib/R/library/Matrix/po/de/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/de/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/en@quot/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/en@quot/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/fr/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/fr/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/it/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/it/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/ko/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/ko/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/lt/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/lt/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/po/pl/LC_MESSAGES/Matrix.mo
./embed-env/lib/R/library/Matrix/po/pl/LC_MESSAGES/R-Matrix.mo
./embed-env/lib/R/library/Matrix/scripts/SuiteSparse.patch
./embed-env/lib/R/library/Matrix/scripts/cholmod.h.patch
./embed-env/lib/R/library/Matrix/scripts/disclaimer.txt
./embed-env/lib/R/library/Matrix/scripts/rules.mk
./embed-env/lib/R/library/Matrix/scripts/rules.sh
./embed-env/lib/R/library/Matrix/scripts/sources.mk
./embed-env/lib/R/library/Matrix/scripts/ssget.sh
./embed-env/lib/R/library/Matrix/test-tools-1.R
./embed-env/lib/R/library/Matrix/test-tools-Matrix.R
./embed-env/lib/R/library/Matrix/test-tools.R
./embed-env/lib/R/library/ellipsis/DESCRIPTION
./embed-env/lib/R/library/ellipsis/INDEX
./embed-env/lib/R/library/ellipsis/LICENSE
./embed-env/lib/R/library/ellipsis/Meta/Rd.rds
./embed-env/lib/R/library/ellipsis/Meta/features.rds
./embed-env/lib/R/library/ellipsis/Meta/hsearch.rds
./embed-env/lib/R/library/ellipsis/Meta/links.rds
./embed-env/lib/R/library/ellipsis/Meta/nsInfo.rds
./embed-env/lib/R/library/ellipsis/Meta/package.rds
./embed-env/lib/R/library/ellipsis/NAMESPACE
./embed-env/lib/R/library/ellipsis/NEWS.md
./embed-env/lib/R/library/ellipsis/R/ellipsis
./embed-env/lib/R/library/ellipsis/R/ellipsis.rdb
./embed-env/lib/R/library/ellipsis/R/ellipsis.rdx
./embed-env/lib/R/library/ellipsis/help/AnIndex
./embed-env/lib/R/library/ellipsis/help/aliases.rds
./embed-env/lib/R/library/ellipsis/help/ellipsis.rdb
./embed-env/lib/R/library/ellipsis/help/ellipsis.rdx
./embed-env/lib/R/library/ellipsis/help/paths.rds
./embed-env/lib/R/library/ellipsis/html/00Index.html
./embed-env/lib/R/library/ellipsis/html/R.css
./embed-env/lib/R/library/ellipsis/libs/ellipsis.so
./embed-env/lib/R/library/mgcv/CITATION
./embed-env/lib/R/library/mgcv/DESCRIPTION
./embed-env/lib/R/library/mgcv/INDEX
./embed-env/lib/R/library/mgcv/Meta/Rd.rds
./embed-env/lib/R/library/mgcv/Meta/data.rds
./embed-env/lib/R/library/mgcv/Meta/features.rds
./embed-env/lib/R/library/mgcv/Meta/hsearch.rds
./embed-env/lib/R/library/mgcv/Meta/links.rds
./embed-env/lib/R/library/mgcv/Meta/nsInfo.rds
./embed-env/lib/R/library/mgcv/Meta/package.rds
./embed-env/lib/R/library/mgcv/NAMESPACE
./embed-env/lib/R/library/mgcv/R/mgcv
./embed-env/lib/R/library/mgcv/R/mgcv.rdb
./embed-env/lib/R/library/mgcv/R/mgcv.rdx
./embed-env/lib/R/library/mgcv/data/columb.polys.rda
./embed-env/lib/R/library/mgcv/data/columb.rda
./embed-env/lib/R/library/mgcv/help/AnIndex
./embed-env/lib/R/library/mgcv/help/aliases.rds
./embed-env/lib/R/library/mgcv/help/mgcv.rdb
./embed-env/lib/R/library/mgcv/help/mgcv.rdx
./embed-env/lib/R/library/mgcv/help/paths.rds
./embed-env/lib/R/library/mgcv/html/00Index.html
./embed-env/lib/R/library/mgcv/html/R.css
./embed-env/lib/R/library/mgcv/libs/mgcv.so
./embed-env/lib/R/library/mgcv/po/de/LC_MESSAGES/R-mgcv.mo
./embed-env/lib/R/library/mgcv/po/de/LC_MESSAGES/mgcv.mo
./embed-env/lib/R/library/mgcv/po/en@quot/LC_MESSAGES/R-mgcv.mo
./embed-env/lib/R/library/mgcv/po/en@quot/LC_MESSAGES/mgcv.mo
./embed-env/lib/R/library/mgcv/po/fr/LC_MESSAGES/R-mgcv.mo
./embed-env/lib/R/library/mgcv/po/fr/LC_MESSAGES/mgcv.mo
./embed-env/lib/R/library/mgcv/po/ko/LC_MESSAGES/R-mgcv.mo
./embed-env/lib/R/library/mgcv/po/ko/LC_MESSAGES/mgcv.mo
./embed-env/lib/R/library/mgcv/po/pl/LC_MESSAGES/R-mgcv.mo
./embed-env/lib/R/library/mgcv/po/pl/LC_MESSAGES/mgcv.mo
./embed-env/lib/R/library/htmltools/DESCRIPTION
./embed-env/lib/R/library/htmltools/INDEX
./embed-env/lib/R/library/htmltools/Meta/Rd.rds
./embed-env/lib/R/library/htmltools/Meta/features.rds
./embed-env/lib/R/library/htmltools/Meta/hsearch.rds
./embed-env/lib/R/library/htmltools/Meta/links.rds
./embed-env/lib/R/library/htmltools/Meta/nsInfo.rds
./embed-env/lib/R/library/htmltools/Meta/package.rds
./embed-env/lib/R/library/htmltools/NAMESPACE
./embed-env/lib/R/library/htmltools/NEWS.md
./embed-env/lib/R/library/htmltools/R/htmltools
./embed-env/lib/R/library/htmltools/R/htmltools.rdb
./embed-env/lib/R/library/htmltools/R/htmltools.rdx
./embed-env/lib/R/library/htmltools/fill/fill.css
./embed-env/lib/R/library/htmltools/help/AnIndex
./embed-env/lib/R/library/htmltools/help/aliases.rds
./embed-env/lib/R/library/htmltools/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/htmltools/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/htmltools/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/htmltools/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/htmltools/help/htmltools.rdb
./embed-env/lib/R/library/htmltools/help/htmltools.rdx
./embed-env/lib/R/library/htmltools/help/paths.rds
./embed-env/lib/R/library/htmltools/html/00Index.html
./embed-env/lib/R/library/htmltools/html/R.css
./embed-env/lib/R/library/htmltools/libs/htmltools.so
./embed-env/lib/R/library/withr/DESCRIPTION
./embed-env/lib/R/library/withr/INDEX
./embed-env/lib/R/library/withr/LICENSE
./embed-env/lib/R/library/withr/Meta/Rd.rds
./embed-env/lib/R/library/withr/Meta/features.rds
./embed-env/lib/R/library/withr/Meta/hsearch.rds
./embed-env/lib/R/library/withr/Meta/links.rds
./embed-env/lib/R/library/withr/Meta/nsInfo.rds
./embed-env/lib/R/library/withr/Meta/package.rds
./embed-env/lib/R/library/withr/Meta/vignette.rds
./embed-env/lib/R/library/withr/NAMESPACE
./embed-env/lib/R/library/withr/NEWS.md
./embed-env/lib/R/library/withr/R/withr
./embed-env/lib/R/library/withr/R/withr.rdb
./embed-env/lib/R/library/withr/R/withr.rdx
./embed-env/lib/R/library/withr/doc/index.html
./embed-env/lib/R/library/withr/doc/withr.R
./embed-env/lib/R/library/withr/doc/withr.Rmd
./embed-env/lib/R/library/withr/doc/withr.html
./embed-env/lib/R/library/withr/help/AnIndex
./embed-env/lib/R/library/withr/help/aliases.rds
./embed-env/lib/R/library/withr/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/withr/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/withr/help/paths.rds
./embed-env/lib/R/library/withr/help/withr.rdb
./embed-env/lib/R/library/withr/help/withr.rdx
./embed-env/lib/R/library/withr/html/00Index.html
./embed-env/lib/R/library/withr/html/R.css
./embed-env/lib/R/library/evaluate/DESCRIPTION
./embed-env/lib/R/library/evaluate/INDEX
./embed-env/lib/R/library/evaluate/LICENSE
./embed-env/lib/R/library/evaluate/Meta/Rd.rds
./embed-env/lib/R/library/evaluate/Meta/features.rds
./embed-env/lib/R/library/evaluate/Meta/hsearch.rds
./embed-env/lib/R/library/evaluate/Meta/links.rds
./embed-env/lib/R/library/evaluate/Meta/nsInfo.rds
./embed-env/lib/R/library/evaluate/Meta/package.rds
./embed-env/lib/R/library/evaluate/NAMESPACE
./embed-env/lib/R/library/evaluate/NEWS.md
./embed-env/lib/R/library/evaluate/R/evaluate
./embed-env/lib/R/library/evaluate/R/evaluate.rdb
./embed-env/lib/R/library/evaluate/R/evaluate.rdx
./embed-env/lib/R/library/evaluate/help/AnIndex
./embed-env/lib/R/library/evaluate/help/aliases.rds
./embed-env/lib/R/library/evaluate/help/evaluate.rdb
./embed-env/lib/R/library/evaluate/help/evaluate.rdx
./embed-env/lib/R/library/evaluate/help/paths.rds
./embed-env/lib/R/library/evaluate/html/00Index.html
./embed-env/lib/R/library/evaluate/html/R.css
./embed-env/lib/R/library/pkgconfig/DESCRIPTION
./embed-env/lib/R/library/pkgconfig/INDEX
./embed-env/lib/R/library/pkgconfig/LICENSE
./embed-env/lib/R/library/pkgconfig/Meta/Rd.rds
./embed-env/lib/R/library/pkgconfig/Meta/features.rds
./embed-env/lib/R/library/pkgconfig/Meta/hsearch.rds
./embed-env/lib/R/library/pkgconfig/Meta/links.rds
./embed-env/lib/R/library/pkgconfig/Meta/nsInfo.rds
./embed-env/lib/R/library/pkgconfig/Meta/package.rds
./embed-env/lib/R/library/pkgconfig/NAMESPACE
./embed-env/lib/R/library/pkgconfig/NEWS.markdown
./embed-env/lib/R/library/pkgconfig/R/pkgconfig
./embed-env/lib/R/library/pkgconfig/R/pkgconfig.rdb
./embed-env/lib/R/library/pkgconfig/R/pkgconfig.rdx
./embed-env/lib/R/library/pkgconfig/README.Rmd
./embed-env/lib/R/library/pkgconfig/README.markdown
./embed-env/lib/R/library/pkgconfig/help/AnIndex
./embed-env/lib/R/library/pkgconfig/help/aliases.rds
./embed-env/lib/R/library/pkgconfig/help/paths.rds
./embed-env/lib/R/library/pkgconfig/help/pkgconfig.rdb
./embed-env/lib/R/library/pkgconfig/help/pkgconfig.rdx
./embed-env/lib/R/library/pkgconfig/html/00Index.html
./embed-env/lib/R/library/pkgconfig/html/R.css
./embed-env/lib/R/library/viridisLite/CITATION
./embed-env/lib/R/library/viridisLite/DESCRIPTION
./embed-env/lib/R/library/viridisLite/INDEX
./embed-env/lib/R/library/viridisLite/LICENSE
./embed-env/lib/R/library/viridisLite/Meta/Rd.rds
./embed-env/lib/R/library/viridisLite/Meta/features.rds
./embed-env/lib/R/library/viridisLite/Meta/hsearch.rds
./embed-env/lib/R/library/viridisLite/Meta/links.rds
./embed-env/lib/R/library/viridisLite/Meta/nsInfo.rds
./embed-env/lib/R/library/viridisLite/Meta/package.rds
./embed-env/lib/R/library/viridisLite/NAMESPACE
./embed-env/lib/R/library/viridisLite/NEWS.md
./embed-env/lib/R/library/viridisLite/R/viridisLite
./embed-env/lib/R/library/viridisLite/R/viridisLite.rdb
./embed-env/lib/R/library/viridisLite/R/viridisLite.rdx
./embed-env/lib/R/library/viridisLite/help/AnIndex
./embed-env/lib/R/library/viridisLite/help/aliases.rds
./embed-env/lib/R/library/viridisLite/help/paths.rds
./embed-env/lib/R/library/viridisLite/help/viridisLite.rdb
./embed-env/lib/R/library/viridisLite/help/viridisLite.rdx
./embed-env/lib/R/library/viridisLite/html/00Index.html
./embed-env/lib/R/library/viridisLite/html/R.css
./embed-env/lib/R/library/RColorBrewer/COPYING
./embed-env/lib/R/library/RColorBrewer/DESCRIPTION
./embed-env/lib/R/library/RColorBrewer/INDEX
./embed-env/lib/R/library/RColorBrewer/Meta/Rd.rds
./embed-env/lib/R/library/RColorBrewer/Meta/features.rds
./embed-env/lib/R/library/RColorBrewer/Meta/hsearch.rds
./embed-env/lib/R/library/RColorBrewer/Meta/links.rds
./embed-env/lib/R/library/RColorBrewer/Meta/nsInfo.rds
./embed-env/lib/R/library/RColorBrewer/Meta/package.rds
./embed-env/lib/R/library/RColorBrewer/NAMESPACE
./embed-env/lib/R/library/RColorBrewer/R/RColorBrewer
./embed-env/lib/R/library/RColorBrewer/R/RColorBrewer.rdb
./embed-env/lib/R/library/RColorBrewer/R/RColorBrewer.rdx
./embed-env/lib/R/library/RColorBrewer/help/AnIndex
./embed-env/lib/R/library/RColorBrewer/help/RColorBrewer.rdb
./embed-env/lib/R/library/RColorBrewer/help/RColorBrewer.rdx
./embed-env/lib/R/library/RColorBrewer/help/aliases.rds
./embed-env/lib/R/library/RColorBrewer/help/paths.rds
./embed-env/lib/R/library/RColorBrewer/html/00Index.html
./embed-env/lib/R/library/RColorBrewer/html/R.css
./embed-env/lib/R/library/R6/DESCRIPTION
./embed-env/lib/R/library/R6/INDEX
./embed-env/lib/R/library/R6/LICENSE
./embed-env/lib/R/library/R6/Meta/Rd.rds
./embed-env/lib/R/library/R6/Meta/features.rds
./embed-env/lib/R/library/R6/Meta/hsearch.rds
./embed-env/lib/R/library/R6/Meta/links.rds
./embed-env/lib/R/library/R6/Meta/nsInfo.rds
./embed-env/lib/R/library/R6/Meta/package.rds
./embed-env/lib/R/library/R6/NAMESPACE
./embed-env/lib/R/library/R6/NEWS.md
./embed-env/lib/R/library/R6/R/R6
./embed-env/lib/R/library/R6/R/R6.rdb
./embed-env/lib/R/library/R6/R/R6.rdx
./embed-env/lib/R/library/R6/help/AnIndex
./embed-env/lib/R/library/R6/help/R6.rdb
./embed-env/lib/R/library/R6/help/R6.rdx
./embed-env/lib/R/library/R6/help/aliases.rds
./embed-env/lib/R/library/R6/help/figures/logo.svg
./embed-env/lib/R/library/R6/help/paths.rds
./embed-env/lib/R/library/R6/html/00Index.html
./embed-env/lib/R/library/R6/html/R.css
./embed-env/lib/R/library/labeling/DESCRIPTION
./embed-env/lib/R/library/labeling/INDEX
./embed-env/lib/R/library/labeling/LICENSE
./embed-env/lib/R/library/labeling/Meta/Rd.rds
./embed-env/lib/R/library/labeling/Meta/features.rds
./embed-env/lib/R/library/labeling/Meta/hsearch.rds
./embed-env/lib/R/library/labeling/Meta/links.rds
./embed-env/lib/R/library/labeling/Meta/nsInfo.rds
./embed-env/lib/R/library/labeling/Meta/package.rds
./embed-env/lib/R/library/labeling/NAMESPACE
./embed-env/lib/R/library/labeling/R/labeling
./embed-env/lib/R/library/labeling/R/labeling.rdb
./embed-env/lib/R/library/labeling/R/labeling.rdx
./embed-env/lib/R/library/labeling/help/AnIndex
./embed-env/lib/R/library/labeling/help/aliases.rds
./embed-env/lib/R/library/labeling/help/labeling.rdb
./embed-env/lib/R/library/labeling/help/labeling.rdx
./embed-env/lib/R/library/labeling/help/paths.rds
./embed-env/lib/R/library/labeling/html/00Index.html
./embed-env/lib/R/library/labeling/html/R.css
./embed-env/lib/R/library/crayon/DESCRIPTION
./embed-env/lib/R/library/crayon/INDEX
./embed-env/lib/R/library/crayon/LICENSE
./embed-env/lib/R/library/crayon/Meta/Rd.rds
./embed-env/lib/R/library/crayon/Meta/features.rds
./embed-env/lib/R/library/crayon/Meta/hsearch.rds
./embed-env/lib/R/library/crayon/Meta/links.rds
./embed-env/lib/R/library/crayon/Meta/nsInfo.rds
./embed-env/lib/R/library/crayon/Meta/package.rds
./embed-env/lib/R/library/crayon/NAMESPACE
./embed-env/lib/R/library/crayon/NEWS.md
./embed-env/lib/R/library/crayon/R/crayon
./embed-env/lib/R/library/crayon/R/crayon.rdb
./embed-env/lib/R/library/crayon/R/crayon.rdx
./embed-env/lib/R/library/crayon/help/AnIndex
./embed-env/lib/R/library/crayon/help/aliases.rds
./embed-env/lib/R/library/crayon/help/crayon.rdb
./embed-env/lib/R/library/crayon/help/crayon.rdx
./embed-env/lib/R/library/crayon/help/paths.rds
./embed-env/lib/R/library/crayon/html/00Index.html
./embed-env/lib/R/library/crayon/html/R.css
./embed-env/lib/R/library/munsell/DESCRIPTION
./embed-env/lib/R/library/munsell/INDEX
./embed-env/lib/R/library/munsell/LICENSE
./embed-env/lib/R/library/munsell/Meta/Rd.rds
./embed-env/lib/R/library/munsell/Meta/features.rds
./embed-env/lib/R/library/munsell/Meta/hsearch.rds
./embed-env/lib/R/library/munsell/Meta/links.rds
./embed-env/lib/R/library/munsell/Meta/nsInfo.rds
./embed-env/lib/R/library/munsell/Meta/package.rds
./embed-env/lib/R/library/munsell/NAMESPACE
./embed-env/lib/R/library/munsell/NEWS.md
./embed-env/lib/R/library/munsell/R/munsell
./embed-env/lib/R/library/munsell/R/munsell.rdb
./embed-env/lib/R/library/munsell/R/munsell.rdx
./embed-env/lib/R/library/munsell/R/sysdata.rdb
./embed-env/lib/R/library/munsell/R/sysdata.rdx
./embed-env/lib/R/library/munsell/help/AnIndex
./embed-env/lib/R/library/munsell/help/aliases.rds
./embed-env/lib/R/library/munsell/help/munsell.rdb
./embed-env/lib/R/library/munsell/help/munsell.rdx
./embed-env/lib/R/library/munsell/help/paths.rds
./embed-env/lib/R/library/munsell/html/00Index.html
./embed-env/lib/R/library/munsell/html/R.css
./embed-env/lib/R/library/munsell/raw/getmunsellmap.R
./embed-env/lib/R/library/munsell/raw/greys.dat
./embed-env/lib/R/library/munsell/raw/real.dat
./embed-env/lib/R/library/lifecycle/DESCRIPTION
./embed-env/lib/R/library/lifecycle/INDEX
./embed-env/lib/R/library/lifecycle/LICENSE
./embed-env/lib/R/library/lifecycle/Meta/Rd.rds
./embed-env/lib/R/library/lifecycle/Meta/features.rds
./embed-env/lib/R/library/lifecycle/Meta/hsearch.rds
./embed-env/lib/R/library/lifecycle/Meta/links.rds
./embed-env/lib/R/library/lifecycle/Meta/nsInfo.rds
./embed-env/lib/R/library/lifecycle/Meta/package.rds
./embed-env/lib/R/library/lifecycle/Meta/vignette.rds
./embed-env/lib/R/library/lifecycle/NAMESPACE
./embed-env/lib/R/library/lifecycle/NEWS.md
./embed-env/lib/R/library/lifecycle/R/lifecycle
./embed-env/lib/R/library/lifecycle/R/lifecycle.rdb
./embed-env/lib/R/library/lifecycle/R/lifecycle.rdx
./embed-env/lib/R/library/lifecycle/doc/communicate.R
./embed-env/lib/R/library/lifecycle/doc/communicate.Rmd
./embed-env/lib/R/library/lifecycle/doc/communicate.html
./embed-env/lib/R/library/lifecycle/doc/index.html
./embed-env/lib/R/library/lifecycle/doc/manage.R
./embed-env/lib/R/library/lifecycle/doc/manage.Rmd
./embed-env/lib/R/library/lifecycle/doc/manage.html
./embed-env/lib/R/library/lifecycle/doc/stages.R
./embed-env/lib/R/library/lifecycle/doc/stages.Rmd
./embed-env/lib/R/library/lifecycle/doc/stages.html
./embed-env/lib/R/library/lifecycle/help/AnIndex
./embed-env/lib/R/library/lifecycle/help/aliases.rds
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-retired.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/lifecycle/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/lifecycle/help/lifecycle.rdb
./embed-env/lib/R/library/lifecycle/help/lifecycle.rdx
./embed-env/lib/R/library/lifecycle/help/macros/lifecycle.Rd
./embed-env/lib/R/library/lifecycle/help/paths.rds
./embed-env/lib/R/library/lifecycle/html/00Index.html
./embed-env/lib/R/library/lifecycle/html/R.css
./embed-env/lib/R/library/gtable/DESCRIPTION
./embed-env/lib/R/library/gtable/INDEX
./embed-env/lib/R/library/gtable/LICENSE
./embed-env/lib/R/library/gtable/Meta/Rd.rds
./embed-env/lib/R/library/gtable/Meta/features.rds
./embed-env/lib/R/library/gtable/Meta/hsearch.rds
./embed-env/lib/R/library/gtable/Meta/links.rds
./embed-env/lib/R/library/gtable/Meta/nsInfo.rds
./embed-env/lib/R/library/gtable/Meta/package.rds
./embed-env/lib/R/library/gtable/Meta/vignette.rds
./embed-env/lib/R/library/gtable/NAMESPACE
./embed-env/lib/R/library/gtable/NEWS.md
./embed-env/lib/R/library/gtable/R/gtable
./embed-env/lib/R/library/gtable/R/gtable.rdb
./embed-env/lib/R/library/gtable/R/gtable.rdx
./embed-env/lib/R/library/gtable/doc/index.html
./embed-env/lib/R/library/gtable/doc/profiling.R
./embed-env/lib/R/library/gtable/doc/profiling.Rmd
./embed-env/lib/R/library/gtable/doc/profiling.html
./embed-env/lib/R/library/gtable/help/AnIndex
./embed-env/lib/R/library/gtable/help/aliases.rds
./embed-env/lib/R/library/gtable/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/gtable/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/gtable/help/gtable.rdb
./embed-env/lib/R/library/gtable/help/gtable.rdx
./embed-env/lib/R/library/gtable/help/paths.rds
./embed-env/lib/R/library/gtable/html/00Index.html
./embed-env/lib/R/library/gtable/html/R.css
./embed-env/lib/R/library/scales/DESCRIPTION
./embed-env/lib/R/library/scales/INDEX
./embed-env/lib/R/library/scales/LICENSE
./embed-env/lib/R/library/scales/Meta/Rd.rds
./embed-env/lib/R/library/scales/Meta/features.rds
./embed-env/lib/R/library/scales/Meta/hsearch.rds
./embed-env/lib/R/library/scales/Meta/links.rds
./embed-env/lib/R/library/scales/Meta/nsInfo.rds
./embed-env/lib/R/library/scales/Meta/package.rds
./embed-env/lib/R/library/scales/NAMESPACE
./embed-env/lib/R/library/scales/NEWS.md
./embed-env/lib/R/library/scales/R/scales
./embed-env/lib/R/library/scales/R/scales.rdb
./embed-env/lib/R/library/scales/R/scales.rdx
./embed-env/lib/R/library/scales/help/AnIndex
./embed-env/lib/R/library/scales/help/aliases.rds
./embed-env/lib/R/library/scales/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/scales/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/scales/help/figures/logo.svg
./embed-env/lib/R/library/scales/help/paths.rds
./embed-env/lib/R/library/scales/help/scales.rdb
./embed-env/lib/R/library/scales/help/scales.rdx
./embed-env/lib/R/library/scales/html/00Index.html
./embed-env/lib/R/library/scales/html/R.css
./embed-env/lib/R/library/vctrs/DESCRIPTION
./embed-env/lib/R/library/vctrs/INDEX
./embed-env/lib/R/library/vctrs/LICENSE
./embed-env/lib/R/library/vctrs/Meta/Rd.rds
./embed-env/lib/R/library/vctrs/Meta/features.rds
./embed-env/lib/R/library/vctrs/Meta/hsearch.rds
./embed-env/lib/R/library/vctrs/Meta/links.rds
./embed-env/lib/R/library/vctrs/Meta/nsInfo.rds
./embed-env/lib/R/library/vctrs/Meta/package.rds
./embed-env/lib/R/library/vctrs/Meta/vignette.rds
./embed-env/lib/R/library/vctrs/NAMESPACE
./embed-env/lib/R/library/vctrs/NEWS.md
./embed-env/lib/R/library/vctrs/R/vctrs
./embed-env/lib/R/library/vctrs/R/vctrs.rdb
./embed-env/lib/R/library/vctrs/R/vctrs.rdx
./embed-env/lib/R/library/vctrs/WORDLIST
./embed-env/lib/R/library/vctrs/doc/index.html
./embed-env/lib/R/library/vctrs/doc/pillar.R
./embed-env/lib/R/library/vctrs/doc/pillar.Rmd
./embed-env/lib/R/library/vctrs/doc/pillar.html
./embed-env/lib/R/library/vctrs/doc/s3-vector.R
./embed-env/lib/R/library/vctrs/doc/s3-vector.Rmd
./embed-env/lib/R/library/vctrs/doc/s3-vector.html
./embed-env/lib/R/library/vctrs/doc/stability.R
./embed-env/lib/R/library/vctrs/doc/stability.Rmd
./embed-env/lib/R/library/vctrs/doc/stability.html
./embed-env/lib/R/library/vctrs/doc/type-size.R
./embed-env/lib/R/library/vctrs/doc/type-size.Rmd
./embed-env/lib/R/library/vctrs/doc/type-size.html
./embed-env/lib/R/library/vctrs/help/AnIndex
./embed-env/lib/R/library/vctrs/help/aliases.rds
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/vctrs/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/vctrs/help/figures/vec-count-deps.svg
./embed-env/lib/R/library/vctrs/help/paths.rds
./embed-env/lib/R/library/vctrs/help/vctrs.rdb
./embed-env/lib/R/library/vctrs/help/vctrs.rdx
./embed-env/lib/R/library/vctrs/html/00Index.html
./embed-env/lib/R/library/vctrs/html/R.css
./embed-env/lib/R/library/vctrs/include/vctrs.c
./embed-env/lib/R/library/vctrs/include/vctrs.h
./embed-env/lib/R/library/vctrs/libs/vctrs.so
./embed-env/lib/R/library/pillar/DESCRIPTION
./embed-env/lib/R/library/pillar/INDEX
./embed-env/lib/R/library/pillar/LICENSE
./embed-env/lib/R/library/pillar/Meta/Rd.rds
./embed-env/lib/R/library/pillar/Meta/features.rds
./embed-env/lib/R/library/pillar/Meta/hsearch.rds
./embed-env/lib/R/library/pillar/Meta/links.rds
./embed-env/lib/R/library/pillar/Meta/nsInfo.rds
./embed-env/lib/R/library/pillar/Meta/package.rds
./embed-env/lib/R/library/pillar/Meta/vignette.rds
./embed-env/lib/R/library/pillar/NAMESPACE
./embed-env/lib/R/library/pillar/NEWS.md
./embed-env/lib/R/library/pillar/R/pillar
./embed-env/lib/R/library/pillar/R/pillar.rdb
./embed-env/lib/R/library/pillar/R/pillar.rdx
./embed-env/lib/R/library/pillar/WORDLIST
./embed-env/lib/R/library/pillar/doc/debugme.R
./embed-env/lib/R/library/pillar/doc/debugme.Rmd
./embed-env/lib/R/library/pillar/doc/debugme.html
./embed-env/lib/R/library/pillar/doc/digits.Rmd
./embed-env/lib/R/library/pillar/doc/digits.html
./embed-env/lib/R/library/pillar/doc/extending.R
./embed-env/lib/R/library/pillar/doc/extending.Rmd
./embed-env/lib/R/library/pillar/doc/extending.html
./embed-env/lib/R/library/pillar/doc/index.html
./embed-env/lib/R/library/pillar/doc/numbers.R
./embed-env/lib/R/library/pillar/doc/numbers.Rmd
./embed-env/lib/R/library/pillar/doc/numbers.html
./embed-env/lib/R/library/pillar/doc/printing.R
./embed-env/lib/R/library/pillar/doc/printing.Rmd
./embed-env/lib/R/library/pillar/doc/printing.html
./embed-env/lib/R/library/pillar/help/AnIndex
./embed-env/lib/R/library/pillar/help/aliases.rds
./embed-env/lib/R/library/pillar/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/pillar/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/pillar/help/paths.rds
./embed-env/lib/R/library/pillar/help/pillar.rdb
./embed-env/lib/R/library/pillar/help/pillar.rdx
./embed-env/lib/R/library/pillar/html/00Index.html
./embed-env/lib/R/library/pillar/html/R.css
./embed-env/lib/R/library/repr/DESCRIPTION
./embed-env/lib/R/library/repr/INDEX
./embed-env/lib/R/library/repr/Meta/Rd.rds
./embed-env/lib/R/library/repr/Meta/features.rds
./embed-env/lib/R/library/repr/Meta/hsearch.rds
./embed-env/lib/R/library/repr/Meta/links.rds
./embed-env/lib/R/library/repr/Meta/nsInfo.rds
./embed-env/lib/R/library/repr/Meta/package.rds
./embed-env/lib/R/library/repr/NAMESPACE
./embed-env/lib/R/library/repr/NEWS.md
./embed-env/lib/R/library/repr/R/repr
./embed-env/lib/R/library/repr/R/repr.rdb
./embed-env/lib/R/library/repr/R/repr.rdx
./embed-env/lib/R/library/repr/help/AnIndex
./embed-env/lib/R/library/repr/help/aliases.rds
./embed-env/lib/R/library/repr/help/paths.rds
./embed-env/lib/R/library/repr/help/repr.rdb
./embed-env/lib/R/library/repr/help/repr.rdx
./embed-env/lib/R/library/repr/html/00Index.html
./embed-env/lib/R/library/repr/html/R.css
./embed-env/lib/R/library/IRdisplay/DESCRIPTION
./embed-env/lib/R/library/IRdisplay/INDEX
./embed-env/lib/R/library/IRdisplay/LICENSE
./embed-env/lib/R/library/IRdisplay/Meta/Rd.rds
./embed-env/lib/R/library/IRdisplay/Meta/features.rds
./embed-env/lib/R/library/IRdisplay/Meta/hsearch.rds
./embed-env/lib/R/library/IRdisplay/Meta/links.rds
./embed-env/lib/R/library/IRdisplay/Meta/nsInfo.rds
./embed-env/lib/R/library/IRdisplay/Meta/package.rds
./embed-env/lib/R/library/IRdisplay/NAMESPACE
./embed-env/lib/R/library/IRdisplay/R/IRdisplay
./embed-env/lib/R/library/IRdisplay/R/IRdisplay.rdb
./embed-env/lib/R/library/IRdisplay/R/IRdisplay.rdx
./embed-env/lib/R/library/IRdisplay/help/AnIndex
./embed-env/lib/R/library/IRdisplay/help/IRdisplay.rdb
./embed-env/lib/R/library/IRdisplay/help/IRdisplay.rdx
./embed-env/lib/R/library/IRdisplay/help/aliases.rds
./embed-env/lib/R/library/IRdisplay/help/paths.rds
./embed-env/lib/R/library/IRdisplay/html/00Index.html
./embed-env/lib/R/library/IRdisplay/html/R.css
./embed-env/lib/R/library/tibble/DESCRIPTION
./embed-env/lib/R/library/tibble/INDEX
./embed-env/lib/R/library/tibble/LICENSE
./embed-env/lib/R/library/tibble/Meta/Rd.rds
./embed-env/lib/R/library/tibble/Meta/features.rds
./embed-env/lib/R/library/tibble/Meta/hsearch.rds
./embed-env/lib/R/library/tibble/Meta/links.rds
./embed-env/lib/R/library/tibble/Meta/nsInfo.rds
./embed-env/lib/R/library/tibble/Meta/package.rds
./embed-env/lib/R/library/tibble/Meta/vignette.rds
./embed-env/lib/R/library/tibble/NAMESPACE
./embed-env/lib/R/library/tibble/NEWS.md
./embed-env/lib/R/library/tibble/R/tibble
./embed-env/lib/R/library/tibble/R/tibble.rdb
./embed-env/lib/R/library/tibble/R/tibble.rdx
./embed-env/lib/R/library/tibble/doc/digits.R
./embed-env/lib/R/library/tibble/doc/digits.Rmd
./embed-env/lib/R/library/tibble/doc/digits.html
./embed-env/lib/R/library/tibble/doc/extending.R
./embed-env/lib/R/library/tibble/doc/extending.Rmd
./embed-env/lib/R/library/tibble/doc/extending.html
./embed-env/lib/R/library/tibble/doc/formats.R
./embed-env/lib/R/library/tibble/doc/formats.Rmd
./embed-env/lib/R/library/tibble/doc/formats.html
./embed-env/lib/R/library/tibble/doc/index.html
./embed-env/lib/R/library/tibble/doc/invariants.R
./embed-env/lib/R/library/tibble/doc/invariants.Rmd
./embed-env/lib/R/library/tibble/doc/invariants.html
./embed-env/lib/R/library/tibble/doc/numbers.R
./embed-env/lib/R/library/tibble/doc/numbers.Rmd
./embed-env/lib/R/library/tibble/doc/numbers.html
./embed-env/lib/R/library/tibble/doc/tibble.R
./embed-env/lib/R/library/tibble/doc/tibble.Rmd
./embed-env/lib/R/library/tibble/doc/tibble.html
./embed-env/lib/R/library/tibble/doc/types.R
./embed-env/lib/R/library/tibble/doc/types.Rmd
./embed-env/lib/R/library/tibble/doc/types.html
./embed-env/lib/R/library/tibble/help/AnIndex
./embed-env/lib/R/library/tibble/help/aliases.rds
./embed-env/lib/R/library/tibble/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-soft-deprecated.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/tibble/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/tibble/help/paths.rds
./embed-env/lib/R/library/tibble/help/tibble.rdb
./embed-env/lib/R/library/tibble/help/tibble.rdx
./embed-env/lib/R/library/tibble/html/00Index.html
./embed-env/lib/R/library/tibble/html/R.css
./embed-env/lib/R/library/tibble/libs/tibble.so
./embed-env/lib/R/library/ggplot2/CITATION
./embed-env/lib/R/library/ggplot2/DESCRIPTION
./embed-env/lib/R/library/ggplot2/INDEX
./embed-env/lib/R/library/ggplot2/LICENSE
./embed-env/lib/R/library/ggplot2/Meta/Rd.rds
./embed-env/lib/R/library/ggplot2/Meta/data.rds
./embed-env/lib/R/library/ggplot2/Meta/features.rds
./embed-env/lib/R/library/ggplot2/Meta/hsearch.rds
./embed-env/lib/R/library/ggplot2/Meta/links.rds
./embed-env/lib/R/library/ggplot2/Meta/nsInfo.rds
./embed-env/lib/R/library/ggplot2/Meta/package.rds
./embed-env/lib/R/library/ggplot2/Meta/vignette.rds
./embed-env/lib/R/library/ggplot2/NAMESPACE
./embed-env/lib/R/library/ggplot2/NEWS.md
./embed-env/lib/R/library/ggplot2/R/ggplot2
./embed-env/lib/R/library/ggplot2/R/ggplot2.rdb
./embed-env/lib/R/library/ggplot2/R/ggplot2.rdx
./embed-env/lib/R/library/ggplot2/data/Rdata.rdb
./embed-env/lib/R/library/ggplot2/data/Rdata.rds
./embed-env/lib/R/library/ggplot2/data/Rdata.rdx
./embed-env/lib/R/library/ggplot2/doc/extending-ggplot2.R
./embed-env/lib/R/library/ggplot2/doc/extending-ggplot2.Rmd
./embed-env/lib/R/library/ggplot2/doc/extending-ggplot2.html
./embed-env/lib/R/library/ggplot2/doc/ggplot2-in-packages.R
./embed-env/lib/R/library/ggplot2/doc/ggplot2-in-packages.Rmd
./embed-env/lib/R/library/ggplot2/doc/ggplot2-in-packages.html
./embed-env/lib/R/library/ggplot2/doc/ggplot2-specs.R
./embed-env/lib/R/library/ggplot2/doc/ggplot2-specs.Rmd
./embed-env/lib/R/library/ggplot2/doc/ggplot2-specs.html
./embed-env/lib/R/library/ggplot2/doc/ggplot2.R
./embed-env/lib/R/library/ggplot2/doc/ggplot2.Rmd
./embed-env/lib/R/library/ggplot2/doc/ggplot2.html
./embed-env/lib/R/library/ggplot2/doc/index.html
./embed-env/lib/R/library/ggplot2/help/AnIndex
./embed-env/lib/R/library/ggplot2/help/aliases.rds
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-archived.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-defunct.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-deprecated.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-experimental.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-maturing.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-questioning.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-stable.svg
./embed-env/lib/R/library/ggplot2/help/figures/lifecycle-superseded.svg
./embed-env/lib/R/library/ggplot2/help/ggplot2.rdb
./embed-env/lib/R/library/ggplot2/help/ggplot2.rdx
./embed-env/lib/R/library/ggplot2/help/paths.rds
./embed-env/lib/R/library/ggplot2/html/00Index.html
./embed-env/lib/R/library/ggplot2/html/R.css
./embed-env/lib/R/modules/lapack.so
./embed-env/lib/R/share/R/REMOVE.R
./embed-env/lib/R/share/R/examples-footer.R
./embed-env/lib/R/share/R/examples-header.R
./embed-env/lib/R/share/R/nspackloader.R
./embed-env/lib/R/share/R/tests-startup.R
./embed-env/lib/R/share/Rd/macros/system.Rd
./embed-env/lib/R/share/dictionaries/R_Rd_files.rds
./embed-env/lib/R/share/dictionaries/R_manuals.rds
./embed-env/lib/R/share/dictionaries/R_vignettes.rds
./embed-env/lib/R/share/dictionaries/en_stats.rds
./embed-env/lib/R/share/encodings/Adobe-glyphlist
./embed-env/lib/R/share/encodings/character-sets
./embed-env/lib/R/share/java/README
./embed-env/lib/R/share/java/getsp.class
./embed-env/lib/R/share/licenses/AGPL-3
./embed-env/lib/R/share/licenses/Artistic-2.0
./embed-env/lib/R/share/licenses/BSD_2_clause
./embed-env/lib/R/share/licenses/BSD_3_clause
./embed-env/lib/R/share/licenses/GPL-2
./embed-env/lib/R/share/licenses/GPL-3
./embed-env/lib/R/share/licenses/LGPL-2
./embed-env/lib/R/share/licenses/LGPL-2.1
./embed-env/lib/R/share/licenses/LGPL-3
./embed-env/lib/R/share/licenses/MIT
./embed-env/lib/R/share/licenses/license.db
./embed-env/lib/R/share/make/basepkg.mk
./embed-env/lib/R/share/make/check_vars_ini.mk
./embed-env/lib/R/share/make/check_vars_out.mk
./embed-env/lib/R/share/make/clean.mk
./embed-env/lib/R/share/make/config.mk
./embed-env/lib/R/share/make/lazycomp.mk
./embed-env/lib/R/share/make/shlib.mk
./embed-env/lib/R/share/make/vars.mk
./embed-env/lib/R/share/make/winshlib.mk
./embed-env/lib/R/share/sh/echo.sh
`


Module["onRuntimeInitialized"] = () => {
    console.log("R is ready");
    // callMain();
    // callMain(["--vanilla", "-e", "print('hello')"])
}

Module["preRun"] = () => {
ENV["R_HOME"] = "/embed-env/lib/R";
ENV["R_INSTALL_LIBRARY"] = "/embed-env/lib/R/library/";
ENV["R_ENVIRON"] = "/embed-env/lib/R/etc/Renviron";
ENV["EDITOR"] = "vim";
// ENV["R_DEFAULT_PACKAGES"] = "base,methods,datasets,grDevices,graphics";
ENV["R_ENABLE_JIT"] = "0";
let all_files = fffiles.split('\n').map(file => file.replace(/^\./, ''));
all_files.shift();
all_files.pop();
console.log("ONE FILES", all_files[0]);
for (let i = 0; i < all_files.length; i++) {
    const file = all_files[i];
    const path_in_virtual_fs = `${file}`;
    const dirname = path_in_virtual_fs.split('/').slice(0, -1).join('/');
    const filename = path_in_virtual_fs.split('/').slice(-1)[0];
    if (filename.endsWith('.png') || filename.endsWith('.svg') ||
        filename.endsWith('.jpg') || filename.endsWith('.pdf') ||
        filename.endsWith('.html') || filename.endsWith('.css')) {
        continue;
    }

    if (dirname.includes('/help/') || dirname.includes('/html/') ||
        dirname.includes('/doc/') || dirname.includes('/vignettes/')) {
            console.log("Skipping file", dirname + filename);
        continue;
    }

    FS.mkdirTree(dirname);
    FS.createPreloadedFile(dirname, filename, `${file}`, true, true);
    // console.log(`Created file ${filename} in ${dirname}`);
    if (i == all_files.length - 1) {
        console.log("All files created");
    }
}
};